[package]
name = "hybrid-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
hybrid-backend = { path = "../backend" }
hybrid-core = { path = "../core" }
hybrid-pipeline = { path = "../pipeline" }
hybrid-scheduler = { path = "../scheduler" }
rayon = "1"
serde_json.workspace = true
tokio.workspace = true
