import os

fn snake_to_pascal(value string) string {
	mut out := ''
	for part in value.split('_') {
		if part.len == 0 {
			continue
		}
		out += part[..1].to_upper() + part[1..]
	}
	return out
}

fn snake_to_camel(value string) string {
	pascal := snake_to_pascal(value)
	if pascal.len == 0 {
		return pascal
	}
	return pascal[..1].to_lower() + pascal[1..]
}

fn parse_patch_types(schema string) ![]string {
	for line in schema.split_into_lines() {
		if !line.contains('"patch_type"') || !line.contains('"enum"') {
			continue
		}
		start := line.index('[') or { continue }
		end := line.last_index(']') or { continue }
		if end <= start {
			continue
		}
		raw_values := line[start + 1..end]
		mut values := []string{}
		for raw in raw_values.split(',') {
			value := raw.trim_space().trim('"')
			if value.len > 0 {
				values << value
			}
		}
		if values.len > 0 {
			return values
		}
	}
	return error('reload patch_type enum not found in schema')
}

fn write_rust(out_path string, values []string) ! {
	mut lines := []string{}
	lines << '// AUTO-GENERATED by shared/protocol/generate_models.v'
	lines << '// Source: shared/protocol/events.schema.json'
	lines << ''
	lines << '#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq)]'
	lines << '#[serde(rename_all = "snake_case")]'
	lines << 'pub enum PatchType {'
	for value in values {
		lines << '    ${snake_to_pascal(value)},'
	}
	lines << '}'
	lines << ''
	os.write_file(out_path, lines.join('\n'))!
}

fn write_swift(out_path string, values []string) ! {
	mut lines := []string{}
	lines << '// AUTO-GENERATED by shared/protocol/generate_models.v'
	lines << '// Source: shared/protocol/events.schema.json'
	lines << ''
	lines << 'public enum GeneratedWirePatchType: String, Codable, Sendable {'
	for value in values {
		lines << '    case ${snake_to_camel(value)} = "${value}"'
	}
	lines << '}'
	lines << ''
	os.write_file(out_path, lines.join('\n'))!
}

fn main() {
	root := os.real_path(os.join_path(os.dir(@FILE), '..', '..'))
	schema_path := os.join_path(root, 'shared', 'protocol', 'events.schema.json')
	rust_out := os.join_path(root, 'runtime', 'hotreload-daemon', 'src', 'generated_protocol.rs')
	swift_out := os.join_path(root, 'runtime', 'swift-preview-host', 'Sources', 'SwiftPreviewHost', 'GeneratedProtocol.swift')

	schema := os.read_file(schema_path) or {
		eprintln('failed to read schema: ${err}')
		exit(1)
	}
	values := parse_patch_types(schema) or {
		eprintln('failed to parse patch types: ${err}')
		exit(1)
	}
	write_rust(rust_out, values) or {
		eprintln('failed to write rust model: ${err}')
		exit(1)
	}
	write_swift(swift_out, values) or {
		eprintln('failed to write swift model: ${err}')
		exit(1)
	}
	println('generated: ${rust_out}')
	println('generated: ${swift_out}')
}
