module main

import os
import x.json2

fn main() {
	root := resolve_root() or { panic(err.msg()) }
	schema_path := os.join_path(root, 'shared/protocol/events.schema.json')
	schema_raw := os.read_file(schema_path) or { panic(err) }
	values := parse_patch_types(schema_raw) or { panic(err.msg()) }

	rust_out := os.join_path(root, 'in-cli/src/hotreload/generated_protocol.rs')
	swift_out := os.join_path(root,
		'runtime/swift-preview-host/Sources/SwiftPreviewHost/GeneratedProtocol.swift')

	write_rust(rust_out, values) or { panic(err) }
	write_swift(swift_out, values) or { panic(err) }

	println('generated: ${rust_out}')
	println('generated: ${swift_out}')
}

fn resolve_root() !string {
	if os.args.len > 1 {
		return os.args[1]
	}
	mut dir := os.getwd()
	for {
		candidate := os.join_path(dir, 'shared/protocol/events.schema.json')
		if os.exists(candidate) {
			return dir
		}
		parent := os.dir(dir)
		if parent == dir {
			return error('could not find repository root containing shared/protocol/events.schema.json (pass root as argv[1])')
		}
		dir = parent
	}
	// Satisfies compiler (loop always returns).
	return error('could not find repository root containing shared/protocol/events.schema.json (pass root as argv[1])')
}

fn parse_patch_types(schema_raw string) ![]string {
	a := json2.decode[json2.Any](schema_raw) or {
		return error('invalid JSON in schema: ${err}')
	}
	root_map := a.as_map()
	defs_any := root_map['\$defs'] or {
		return error('schema missing \$defs')
	}
	defs_map := defs_any.as_map()
	rp_any := defs_map['ReloadPatch'] or {
		return error('schema missing ReloadPatch')
	}
	rp_map := rp_any.as_map()
	props_any := rp_map['properties'] or {
		return error('schema missing ReloadPatch.properties')
	}
	props_map := props_any.as_map()
	pt_any := props_map['patch_type'] or {
		return error('schema missing ReloadPatch.properties.patch_type')
	}
	pt_map := pt_any.as_map()
	enum_any := pt_map['enum'] or {
		return error('schema missing \$defs.ReloadPatch.properties.patch_type.enum')
	}
	enum_arr := enum_any.arr()
	if enum_arr.len == 0 {
		return error('patch_type enum is empty')
	}
	mut out := []string{}
	for item in enum_arr {
		out << item.str()
	}
	return out
}

fn snake_to_pascal(value string) string {
	parts := value.split('_')
	mut acc := ''
	for part in parts {
		if part.len == 0 {
			continue
		}
		head := part[..1].to_upper()
		tail := if part.len > 1 { part[1..] } else { '' }
		acc += head + tail
	}
	return acc
}

fn snake_to_camel(value string) string {
	pascal := snake_to_pascal(value)
	if pascal.len == 0 {
		return ''
	}
	return pascal[..1].to_lower() + pascal[1..]
}

fn write_rust(out_path string, values []string) ! {
	mut lines := []string{}
	lines << '// AUTO-GENERATED by inauguration protocol-gen (V)'
	lines << '// Source: shared/protocol/events.schema.json'
	lines << ''
	lines << '#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq)]'
	lines << '#[serde(rename_all = "snake_case")]'
	lines << 'pub enum PatchType {'
	for v in values {
		lines << '    ${snake_to_pascal(v)},'
	}
	lines << '}'
	lines << ''
	os.write_file(out_path, lines.join('\n')) or { return err }
}

fn write_swift(out_path string, values []string) ! {
	mut lines := []string{}
	lines << '// AUTO-GENERATED by inauguration protocol-gen (V)'
	lines << '// Source: shared/protocol/events.schema.json'
	lines << ''
	lines << 'public enum GeneratedWirePatchType: String, Codable, Sendable {'
	for v in values {
		lines << '    case ${snake_to_camel(v)} = "${v}"'
	}
	lines << '}'
	lines << ''
	os.write_file(out_path, lines.join('\n')) or { return err }
}
