#!/usr/bin/env bash
# Compare default vs harden emit for anti-decomp smoke metrics.
# Prefer Ghidra analyzeHeadless when available; always emit objdump/nm fallback.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SAMPLE="${SAMPLE:-examples/compile/antidecomp_sample.in}"
OUT_DIR="${OUT_DIR:-target/in/antidecomp-smoke}"
BENCH_MD="${BENCH_MD:-docs/benchmarks/ghidra-antidecomp-smoke.md}"
SKIP_MD="${SKIP_MD:-docs/benchmarks/ghidra-antidecomp-SKIPPED.md}"
TRIPLE="${TRIPLE:-x86_64-unknown-none}"
ENTRY="${ENTRY:-main}"

mkdir -p "$OUT_DIR" "$(dirname "$BENCH_MD")"

IN_BIN="${IN_BIN:-}"
if [[ -z "$IN_BIN" ]]; then
  if [[ -x "$ROOT/in-cli/target/debug/in" ]]; then
    IN_BIN="$ROOT/in-cli/target/debug/in"
  elif command -v in >/dev/null 2>&1; then
    IN_BIN="$(command -v in)"
  else
    echo "building in-cli..."
    cargo build --manifest-path "$ROOT/in-cli/Cargo.toml" -q
    IN_BIN="$ROOT/in-cli/target/debug/in"
  fi
fi

build_one() {
  local profile="$1"
  local out="$OUT_DIR/sample-${profile}.o"
  echo "==> compile profile=${profile}" >&2
  "$IN_BIN" compile \
    --path "$SAMPLE" \
    --target native \
    --target-triple "$TRIPLE" \
    --linkage static-lib \
    --entry "$ENTRY" \
    --out "$out" \
    --profile "$profile" >&2
  if [[ ! -f "$out" ]]; then
    echo "compile failed for profile=${profile}" >&2
    exit 1
  fi
  printf '%s' "$out"
}

DEFAULT_OBJ="$(build_one default)"
HARDEN_OBJ="$(build_one harden)"

metric_file() {
  local obj="$1"
  local label="$2"
  local meta="$OUT_DIR/${label}.metrics.txt"
  {
    echo "file: $obj"
    echo "size_bytes: $(wc -c < "$obj" | tr -d ' ')"
    if command -v nm >/dev/null 2>&1; then
      echo "--- nm ---"
      nm -g "$obj" 2>/dev/null || nm "$obj" 2>/dev/null || true
      echo "named_symbols: $(nm "$obj" 2>/dev/null | grep -c ' [Tt] ' || true)"
      echo "hashed_symbols: $(nm "$obj" 2>/dev/null | grep -c '_H[0-9a-f]' || true)"
    fi
    if command -v objdump >/dev/null 2>&1; then
      echo "--- objdump -d (summary) ---"
      local disasm
      disasm="$(objdump -d "$obj" 2>/dev/null || true)"
      echo "disasm_lines: $(printf '%s\n' "$disasm" | wc -l | tr -d ' ')"
      echo "push_rbx_count: $(printf '%s\n' "$disasm" | grep -c 'push *%rbx' || true)"
      echo "classic_prologue_mov: $(printf '%s\n' "$disasm" | grep -c 'mov *%rsp,%rbp' || true)"
      echo "xor_imm_noise: $(printf '%s\n' "$disasm" | grep -c 'xor' || true)"
    fi
  } > "$meta"
  cat "$meta"
}

echo "==> metrics"
DEFAULT_METRICS="$(metric_file "$DEFAULT_OBJ" default)"
HARDEN_METRICS="$(metric_file "$HARDEN_OBJ" harden)"

HARDER=0
# Heuristics: harden should show hashed symbols and/or push %rbx and/or larger size
H_SIZE=$(wc -c < "$HARDEN_OBJ" | tr -d ' ')
D_SIZE=$(wc -c < "$DEFAULT_OBJ" | tr -d ' ')
H_HASH=$(nm "$HARDEN_OBJ" 2>/dev/null | grep -c '_H[0-9a-f]' || true)
D_HASH=$(nm "$DEFAULT_OBJ" 2>/dev/null | grep -c '_H[0-9a-f]' || true)
H_RBX=$(objdump -d "$HARDEN_OBJ" 2>/dev/null | grep -c 'push *%rbx' || true)

if [[ "$H_HASH" -gt "$D_HASH" ]]; then HARDER=1; fi
if [[ "$H_RBX" -gt 0 ]]; then HARDER=1; fi
if [[ "$H_SIZE" -ge "$D_SIZE" && "$H_HASH" -gt 0 ]]; then HARDER=1; fi

GHIDRA_NOTE="Ghidra not run"
if [[ -n "${GHIDRA_INSTALL_DIR:-}" && -x "${GHIDRA_INSTALL_DIR}/support/analyzeHeadless" ]]; then
  if command -v java >/dev/null 2>&1; then
    GHIDRA_OUT="$OUT_DIR/ghidra"
    mkdir -p "$GHIDRA_OUT"
    "${GHIDRA_INSTALL_DIR}/support/analyzeHeadless" \
      "$GHIDRA_OUT" AntidecompSmoke \
      -import "$DEFAULT_OBJ" -import "$HARDEN_OBJ" \
      -deleteProject || true
    GHIDRA_NOTE="analyzeHeadless invoked; inspect $GHIDRA_OUT"
  else
    GHIDRA_NOTE="GHIDRA_INSTALL_DIR set but java missing"
  fi
else
  cat > "$SKIP_MD" << SKIP
# Ghidra antidecomp smoke — skipped

Ghidra headless was not available on this host.

## Install (optional)

1. Install a JDK 17+ (\`java -version\`).
2. Download Ghidra from https://ghidra-sre.org/ and unpack.
3. Export \`GHIDRA_INSTALL_DIR=/path/to/ghidra_*\`.
4. Re-run \`bash scripts/ghidra-antidecomp-smoke.sh\`.

Objdump/nm fallback metrics were still written to \`$BENCH_MD\`.
SKIP
fi

{
  echo "# Ghidra / objdump anti-decomp smoke"
  echo
  echo "Generated by \`scripts/ghidra-antidecomp-smoke.sh\`."
  echo
  echo "- sample: \`$SAMPLE\`"
  echo "- triple: \`$TRIPLE\`"
  echo "- default object: \`$DEFAULT_OBJ\` ($D_SIZE bytes)"
  echo "- harden object: \`$HARDEN_OBJ\` ($H_SIZE bytes)"
  echo "- hashed symbols default/harden: $D_HASH / $H_HASH"
  echo "- harden push %rbx count: $H_RBX"
  echo "- harder_heuristic: $HARDER"
  echo "- ghidra: $GHIDRA_NOTE"
  echo
  echo "## Default metrics"
  echo '```'
  echo "$DEFAULT_METRICS"
  echo '```'
  echo
  echo "## Harden metrics"
  echo '```'
  echo "$HARDEN_METRICS"
  echo '```'
} > "$BENCH_MD"

echo "wrote $BENCH_MD"
if [[ "$HARDER" -ne 1 ]]; then
  echo "warning: harden did not look harder by heuristics (continuing; check metrics)" >&2
fi
echo "OK"
