// AUTO-GENERATED by inauguration protocol-gen (Rust)
// Source: shared/protocol/events.schema.json

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PatchType {
    ViewBody,
    Modifier,
    FullModule,
}
