// AUTO-GENERATED by shared/protocol/generate_models.v
// Source: shared/protocol/events.schema.json

public enum GeneratedWirePatchType: String, Codable, Sendable {
    case viewBody = "view_body"
    case modifier = "modifier"
    case fullModule = "full_module"
}
