// AUTO-GENERATED by inauguration protocol-gen (Rust)
// Source: shared/protocol/events.schema.json

public enum GeneratedWirePatchType: String, Codable, Sendable {
    case viewBody = "view_body"
    case modifier = "modifier"
    case fullModule = "full_module"
}

public enum GeneratedWireReloadDecision: String, Codable, Sendable {
    case patchApplied = "patch_applied"
    case restartRequired = "restart_required"
    case compileFailed = "compile_failed"
    case abiLayoutMismatch = "abi_layout_mismatch"
    case abiSymbolMissing = "abi_symbol_missing"
    case abiAllocError = "abi_alloc_error"
    case abiPanic = "abi_panic"
}
