name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  in-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test in-cli
        run: cargo test
        working-directory: in-cli

  rust-driver-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test hybrid-cli package
        run: cargo test -p hybrid-cli
        working-directory: compiler/rust-driver
