//! Core IR → C code emitter.
//!
//! Vlang-style C backend: emit portable C99, let GCC/Clang handle optimization.
//! Compile with: zig cc -c -target x86_64-freestanding -ffreestanding -O2 kernel.c

use crate::core_ir::{Decl, Expr, Stmt, Typ, UnifiedModule};

fn ctype(typ: &Typ) -> &str {
    match typ {
        Typ::Int => "int64_t",
        Typ::Bool => "uint8_t",
        Typ::String => "int64_t",
        Typ::Void => "void",
        Typ::Named(_) => "int64_t",
        _ => "int64_t",
    }
}

pub fn emit_c_module(module: &UnifiedModule) -> Result<String, String> {
    let mut func_names: Vec<String> = Vec::new();
    for decl in &module.decls {
        if let Decl::Function { name, .. } = decl {
            func_names.push(name.clone());
        }
    }
    let mut ctx = Ctx::new(func_names);

    ctx.line("/* Generated by Inauguration C backend */");
    ctx.line("#include <stdint.h>");
    ctx.line("#include <stddef.h>");
    ctx.line("");

    // Struct definitions
    for decl in &module.decls {
        if let Decl::Struct { name, fields, .. } = decl {
            ctx.push(&format!("struct {} {{", name));
            ctx.indent();
            for (fname, ftype) in fields {
                ctx.push(&format!("{} {};", ctype(ftype), fname));
            }
            ctx.dedent();
            ctx.line("};");
            ctx.line("");
        }
    }

    // Globals with fixed addresses (section attribute for linker placement)
    let has_globals = module.decls.iter().any(|d| matches!(d, Decl::Global { .. }));
    if has_globals {
        for decl in &module.decls {
            if let Decl::Global { name, typ, init, .. } = decl {
                let init_s = match init {
                    Some(e) => format!(" = {}", ctx.expr_str(e)),
                    None => String::new(),
                };
                ctx.push(&format!("volatile {} {}{};", ctype(typ), name, init_s));
            }
        }
        ctx.line("");
    }

    // Function declarations
    for decl in &module.decls {
        if let Decl::Function { name, params, ret, .. } = decl {
            let ps: Vec<String> = params.iter().map(|(n, t)| format!("{} {}", ctype(t), n)).collect();
            ctx.push(&format!("{} {}({});", ctype(ret), name, ps.join(", ")));
        }
    }

    // Function definitions
    for decl in &module.decls {
        if let Decl::Function { name, params, ret, body, .. } = decl {
            emit_fn_def(&mut ctx, name, params, ret, body);
        }
    }

    // Component metadata as comments
    for decl in &module.decls {
        if let Decl::Component { name, target, deterministic, .. } = decl {
            ctx.push(&format!("/* component: {} target:{} deterministic:{} */", name, target, deterministic));
        }
    }

    Ok(ctx.out)
}

struct Ctx {
    out: String,
    indent_lvl: u32,
    func_names: Vec<String>,
}

impl Ctx {
    fn new(func_names: Vec<String>) -> Self {
        Self { out: String::new(), indent_lvl: 0, func_names }
    }
    fn line(&mut self, s: &str) { self.out.push_str(s); self.out.push('\n'); }
    fn push(&mut self, s: &str) {
        for _ in 0..self.indent_lvl { self.out.push_str("  "); }
        self.out.push_str(s); self.out.push('\n');
    }
    fn indent(&mut self) { self.indent_lvl += 1; }
    fn dedent(&mut self) { self.indent_lvl = self.indent_lvl.saturating_sub(1); }
    fn is_func(&self, name: &str) -> bool { self.func_names.iter().any(|n| n == name) }

    fn expr_str(&self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit(n) => {
                format!("INT64_C({})", n)
            }
            Expr::BoolLit(b) => if *b { "1".into() } else { "0".into() },
            Expr::StringLit(s) => {
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
                format!("(uint64_t)(\"{}\")", escaped)
            }
            Expr::Ident(name) => {
                if self.is_func(name) {
                    // Function name used as value → cast to uint64_t
                    format!("(uint64_t)({})", name)
                } else {
                    name.clone()
                }
            }
            Expr::Binary { op, lhs, rhs } => {
                let (l, r) = (self.expr_str(lhs), self.expr_str(rhs));
                match op.as_str() {
                    "land" => format!("({} && {})", l, r), "lor" => format!("({} || {})", l, r),
                    "eq" => format!("({} == {})", l, r), "neq" => format!("({} != {})", l, r),
                    "lt" => format!("({} < {})", l, r), "gt" => format!("({} > {})", l, r),
                    "le" => format!("({} <= {})", l, r), "ge" => format!("({} >= {})", l, r),
                    "add" => format!("({} + {})", l, r), "sub" => format!("({} - {})", l, r),
                    "mul" => format!("({} * {})", l, r), "div" => format!("({} / {})", l, r),
                    "mod" => format!("({} % {})", l, r),
                    "band" => format!("({} & {})", l, r), "bor" => format!("({} | {})", l, r),
                    "xor" => format!("({} ^ {})", l, r),
                    "shl" => format!("({} << {})", l, r), "shr" => format!("({} >> {})", l, r),
                    _ => format!("({} {} {})", l, op, r),
                }
            }
            Expr::Unary { op, expr } => {
                let e = self.expr_str(expr);
                match op.as_str() { "neg" => format!("(-{})", e), "not" => format!("(!{})", e), _ => format!("({}{})", op, e) }
            }
            Expr::Call { callee, args } => {
                if let Expr::Ident(name) = &**callee {
                    self.intrinsic_or_call(name, args)
                } else {
                    let callee_s = self.expr_str(callee);
                    let as_: Vec<String> = args.iter().map(|a| format!("({})", self.expr_str(a))).collect();
                    format!("{}({})", callee_s, as_.join(", "))
                }
            }
            Expr::Field { base, name } => format!("({}).{}", self.expr_str(base), name),
            Expr::StructInit { name, fields } => {
                let fs: Vec<String> = fields.iter().map(|(fn_, fe)| format!(".{}={}", fn_, self.expr_str(fe))).collect();
                format!("((struct {}){{{}}})", name, fs.join(","))
            }
            Expr::Index { base, index } => {
                format!("(*(volatile int64_t*)({} + {} * 8))", self.expr_str(base), self.expr_str(index))
            }
            _ => "/* unhandled */".into(),
        }
    }

    fn intrinsic_or_call(&self, name: &str, args: &[Expr]) -> String {
        let a = |i: usize| -> String { if i < args.len() { self.expr_str(&args[i]) } else { "0".into() } };
        match name {
            "outb" => {
                let p = a(0); let v = a(1);
                format!("__extension__({{ __asm__ volatile(\"outb %0, %1\" : : \"a\"((uint8_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})")
            }
            "inb" => {
                let p = a(0);
                format!("__extension__({{ uint8_t _v; __asm__ volatile(\"inb %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})")
            }
            "outl" => {
                let p = a(0); let v = a(1);
                format!("__extension__({{ __asm__ volatile(\"outl %0, %1\" : : \"a\"((uint32_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})")
            }
            "inl" => {
                let p = a(0);
                format!("__extension__({{ uint32_t _v; __asm__ volatile(\"inl %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})")
            }
            "hlt" => "__extension__({ __asm__ volatile(\"hlt\" : : : \"memory\"); })".into(),
            "cli" => "__extension__({ __asm__ volatile(\"cli\" : : : \"memory\"); })".into(),
            "sti" => "__extension__({ __asm__ volatile(\"sti\" : : : \"memory\"); })".into(),
            "invlpg" => format!("__extension__({{ __asm__ volatile(\"invlpg (%0)\" : : \"r\"({}) : \"memory\"); }})", a(0)),
            "lidt" => {
                // lidt(base, _) — IDTR struct already stored at base by store16/store64
                format!("__extension__({{ __asm__ volatile(\"lidt (%0)\" : : \"r\"({}) : \"memory\"); }})", a(0))
            }
            "read_cr2" => "__extension__({ uint64_t _v; __asm__ volatile(\"mov %%cr2, %0\" : \"=r\"(_v)); _v; })".into(),
            "load8" => format!("(*(volatile uint8_t*)({}))", a(0)),
            "load16" => format!("(*(volatile uint16_t*)({}))", a(0)),
            "load32" => format!("(*(volatile uint32_t*)({}))", a(0)),
            "load64" => format!("(*(volatile uint64_t*)({}))", a(0)),
            "store8" => format!("__extension__({{ *(volatile uint8_t*)({}) = (uint8_t)({}); }})", a(0), a(1)),
            "store16" => format!("__extension__({{ *(volatile uint16_t*)({}) = (uint16_t)({}); }})", a(0), a(1)),
            "store32" => format!("__extension__({{ *(volatile uint32_t*)({}) = (uint32_t)({}); }})", a(0), a(1)),
            "store64" => format!("__extension__({{ *(volatile uint64_t*)({}) = (uint64_t)({}); }})", a(0), a(1)),
            "invoke" if args.len() == 1 => format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(0)),
            "invoke" if args.len() == 2 => format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1)),
            "invoke" if args.len() == 3 => format!("((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})", a(0), a(1), a(2)),
            "invoke1" if args.len() == 2 => format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1)),
            "invoke2" if args.len() == 3 => format!("((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})", a(0), a(1), a(2)),
            _ => {
                let as_: Vec<String> = args.iter().map(|a| self.expr_str(a)).collect();
                format!("{}({})", name, as_.join(", "))
            }
        }
    }
}

fn emit_fn_def(ctx: &mut Ctx, name: &str, params: &[(String, Typ)], ret: &Typ, body: &[Stmt]) {
    let ps: Vec<String> = params.iter().map(|(n, t)| format!("{} {}", ctype(t), n)).collect();
    // Mark every function used so linker GC doesn't discard through pointer calls
    let sec = if name == "kernel_entry" { " __attribute__((section(\".text.entry\")))" } else { "" };
    let attr = format!("__attribute__((used)){}", sec);
    let sig = format!("{}{} {}({})", attr, ctype(ret), name, ps.join(", "));
    ctx.push(&format!("{} {{", sig));
    ctx.indent();

    // Collect and declare local variables
    let mut locals: Vec<String> = Vec::new();
    collect_locals(body, &mut locals);
    for n in &locals {
        ctx.push(&format!("int64_t {};", n));
    }

    for stmt in body { emit_stmt(ctx, stmt); }
    if ret == &Typ::Void { ctx.push("return;"); }

    ctx.dedent();
    ctx.line("}");
    ctx.line("");
}

fn emit_stmt(ctx: &mut Ctx, stmt: &Stmt) {
    match stmt {
        Stmt::Let(name, _, expr) => { ctx.push(&format!("{} = {};", name, ctx.expr_str(expr))); }
        Stmt::Assign(name, expr) => { ctx.push(&format!("{} = {};", name, ctx.expr_str(expr))); }
        Stmt::IndexAssign { base, index, value } => {
            ctx.push(&format!("*(volatile uint64_t*)({} + {} * 8) = {};",
                ctx.expr_str(base), ctx.expr_str(index), ctx.expr_str(value)));
        }
        Stmt::Return(e) => {
            match e { Some(x) => ctx.push(&format!("return {};", ctx.expr_str(x))), None => ctx.push("return;") }
        }
        Stmt::If { cond, then_body, else_body } => {
            ctx.push(&format!("if ({}) {{", ctx.expr_str(cond)));
            ctx.indent();
            for s in then_body { emit_stmt(ctx, s); }
            ctx.dedent();
            if !else_body.is_empty() {
                ctx.line("} else {");
                ctx.indent();
                for s in else_body { emit_stmt(ctx, s); }
                ctx.dedent();
            }
            ctx.line("}");
        }
        Stmt::Loop { cond, body, .. } => {
            match cond { Some(c) => ctx.push(&format!("while ({}) {{", ctx.expr_str(c))), None => ctx.line("while (1) {") }
            ctx.indent();
            for s in body { emit_stmt(ctx, s); }
            ctx.dedent();
            ctx.line("}");
        }
        Stmt::Expr(e) => { ctx.push(&format!("{};", ctx.expr_str(e))); }
        Stmt::Break => { ctx.line("break;"); }
        _ => { ctx.line("/* unhandled stmt */"); }
    }
}

fn collect_locals(stmts: &[Stmt], locals: &mut Vec<String>) {
    for stmt in stmts {
        match stmt {
            Stmt::Let(name, _, _) => { if !locals.contains(name) { locals.push(name.clone()); } }
            Stmt::If { then_body, else_body, .. } => { collect_locals(then_body, locals); collect_locals(else_body, locals); }
            Stmt::Loop { body, .. } => { collect_locals(body, locals); }
            _ => {}
        }
    }
}
