//! Core IR → C code emitter.
//!
//! Vlang-style C backend: emit portable C99, let GCC/Clang handle optimization.
//! Compile with: zig cc -c -target x86_64-freestanding -ffreestanding -O2 kernel.c

use crate::core_ir::{Decl, Expr, LoopKind, Stmt, Typ, UnifiedModule};

fn ctype(typ: &Typ) -> String {
    match typ.canonical() {
        Typ::Int => "int64_t".into(),
        Typ::Bool => "uint8_t".into(),
        Typ::Float => "double".into(),
        Typ::String => "const char*".into(),
        Typ::Void => "void".into(),
        Typ::Array(inner) | Typ::Vector(inner) => format!("{}*", ctype(&inner)),
        Typ::Named(name) => format!("struct {}", sanitize_ident(&name)),
        Typ::Generic(_) => "int64_t".into(),
    }
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Emit a complete C translation unit from Core IR.
pub fn emit_c_module(module: &UnifiedModule) -> Result<String, String> {
    let mut func_names: Vec<String> = Vec::new();
    for decl in &module.decls {
        match decl {
            Decl::Function { name, .. } => func_names.push(name.clone()),
            Decl::Class { methods, .. } => {
                for m in methods {
                    if let Decl::Function { name, .. } = m {
                        func_names.push(name.clone());
                    }
                }
            }
            _ => {}
        }
    }
    let mut ctx = Ctx::new(func_names);

    ctx.line("/* Generated by Inauguration C backend */");
    ctx.line("#include <stdint.h>");
    ctx.line("#include <stddef.h>");
    ctx.line("");

    if let Some(pkg) = &module.identity.package {
        ctx.push(&format!("/* package: {} */", pkg));
    }
    if let Some(mod_name) = &module.identity.module {
        ctx.push(&format!("/* module: {} */", mod_name));
    }
    if module.identity.package.is_some() || module.identity.module.is_some() {
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Struct { name, fields, .. } = decl {
            ctx.push(&format!("struct {} {{", sanitize_ident(name)));
            ctx.indent();
            if fields.is_empty() {
                ctx.push("char _pad;");
            } else {
                for (fname, ftype) in fields {
                    ctx.push(&format!("{} {};", ctype(ftype), sanitize_ident(fname)));
                }
            }
            ctx.dedent();
            ctx.line("};");
            ctx.line("");
        }
    }

    // Classes lower as structs + free methods (self first param).
    for decl in &module.decls {
        if let Decl::Class {
            name,
            fields,
            methods,
            ..
        } = decl
        {
            ctx.push(&format!("struct {} {{", sanitize_ident(name)));
            ctx.indent();
            if fields.is_empty() {
                ctx.push("char _pad;");
            } else {
                for (fname, ftype) in fields {
                    ctx.push(&format!("{} {};", ctype(ftype), sanitize_ident(fname)));
                }
            }
            ctx.dedent();
            ctx.line("};");
            ctx.line("");
            for m in methods {
                if let Decl::Function {
                    name: mname,
                    params,
                    ret,
                    body,
                    ..
                } = m
                {
                    let mut full_params = vec![("self".to_string(), Typ::Named(name.clone()))];
                    full_params.extend(params.iter().cloned());
                    emit_fn_def(
                        &mut ctx,
                        &format!("{}_{}", sanitize_ident(name), sanitize_ident(mname)),
                        &full_params,
                        ret,
                        body,
                    );
                }
            }
        }
    }

    for decl in &module.decls {
        if let Decl::Interface { name, methods, .. } = decl {
            ctx.push(&format!("/* interface {} */", sanitize_ident(name)));
            for m in methods {
                let ps: Vec<String> = m
                    .params
                    .iter()
                    .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                    .collect();
                ctx.push(&format!(
                    "/* {} {}({}); */",
                    ctype(&m.ret),
                    sanitize_ident(&m.name),
                    ps.join(", ")
                ));
            }
            ctx.line("");
        }
    }

    let has_globals = module
        .decls
        .iter()
        .any(|d| matches!(d, Decl::Global { .. }));
    if has_globals {
        for decl in &module.decls {
            if let Decl::Global {
                name, typ, init, ..
            } = decl
            {
                let init_s = match init {
                    Some(e) => format!(" = {}", ctx.expr_str(e)),
                    None => String::new(),
                };
                ctx.push(&format!(
                    "volatile {} {}{};",
                    ctype(typ),
                    sanitize_ident(name),
                    init_s
                ));
            }
        }
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Function {
            name, params, ret, ..
        } = decl
        {
            let ps: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                .collect();
            ctx.push(&format!(
                "{} {}({});",
                ctype(ret),
                sanitize_ident(name),
                ps.join(", ")
            ));
        }
    }
    if module
        .decls
        .iter()
        .any(|d| matches!(d, Decl::Function { .. }))
    {
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Function {
            name,
            params,
            ret,
            body,
            ..
        } = decl
        {
            emit_fn_def(&mut ctx, name, params, ret, body);
        }
    }

    for decl in &module.decls {
        if let Decl::Component {
            name,
            target,
            deterministic,
            ..
        } = decl
        {
            ctx.push(&format!(
                "/* component: {} target:{} deterministic:{} */",
                name, target, deterministic
            ));
        }
    }

    Ok(ctx.out)
}

struct Ctx {
    out: String,
    indent_lvl: u32,
    func_names: Vec<String>,
}

impl Ctx {
    fn new(func_names: Vec<String>) -> Self {
        Self {
            out: String::new(),
            indent_lvl: 0,
            func_names,
        }
    }

    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn push(&mut self, s: &str) {
        for _ in 0..self.indent_lvl {
            self.out.push_str("  ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn indent(&mut self) {
        self.indent_lvl += 1;
    }

    fn dedent(&mut self) {
        self.indent_lvl = self.indent_lvl.saturating_sub(1);
    }

    fn is_func(&self, name: &str) -> bool {
        self.func_names.iter().any(|n| n == name)
    }

    fn expr_str(&self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit(n) => format!("INT64_C({})", n),
            Expr::FloatLit(f) => {
                let bits = f.0;
                if bits.is_finite() {
                    format!("{:?}", bits)
                } else {
                    "0.0".into()
                }
            }
            Expr::BoolLit(b) => {
                if *b {
                    "1".into()
                } else {
                    "0".into()
                }
            }
            Expr::StringLit(s) => {
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
                format!("\"{}\"", escaped)
            }
            Expr::Ident(name) => {
                if self.is_func(name) {
                    format!("(uint64_t)({})", sanitize_ident(name))
                } else {
                    sanitize_ident(name)
                }
            }
            Expr::Binary { op, lhs, rhs } => {
                let (l, r) = (self.expr_str(lhs), self.expr_str(rhs));
                match op.as_str() {
                    "land" | "&&" => format!("({} && {})", l, r),
                    "lor" | "||" => format!("({} || {})", l, r),
                    "eq" | "==" => format!("({} == {})", l, r),
                    "neq" | "!=" => format!("({} != {})", l, r),
                    "lt" | "<" => format!("({} < {})", l, r),
                    "gt" | ">" => format!("({} > {})", l, r),
                    "le" | "<=" => format!("({} <= {})", l, r),
                    "ge" | ">=" => format!("({} >= {})", l, r),
                    "add" | "+" => format!("({} + {})", l, r),
                    "sub" | "-" => format!("({} - {})", l, r),
                    "mul" | "*" => format!("({} * {})", l, r),
                    "div" | "/" => format!("({} / {})", l, r),
                    "mod" | "%" => format!("({} % {})", l, r),
                    "band" | "&" => format!("({} & {})", l, r),
                    "bor" | "|" => format!("({} | {})", l, r),
                    "xor" | "^" => format!("({} ^ {})", l, r),
                    "shl" | "<<" => format!("({} << {})", l, r),
                    "shr" | ">>" => format!("({} >> {})", l, r),
                    _ => format!("({} /*op:{}*/ {})", l, op, r),
                }
            }
            Expr::Unary { op, expr } => {
                let e = self.expr_str(expr);
                match op.as_str() {
                    "neg" | "-" => format!("(-{})", e),
                    "not" | "!" => format!("(!{})", e),
                    _ => format!("(/*op:{}*/{})", op, e),
                }
            }
            Expr::Call { callee, args } => {
                if let Expr::Ident(name) = &**callee {
                    self.intrinsic_or_call(name, args)
                } else {
                    let callee_s = self.expr_str(callee);
                    let as_: Vec<String> = args.iter().map(|a| self.expr_str(a)).collect();
                    format!("({})({})", callee_s, as_.join(", "))
                }
            }
            Expr::Field { base, name } => {
                format!("({}).{}", self.expr_str(base), sanitize_ident(name))
            }
            Expr::StructInit { name, fields } => {
                let fs: Vec<String> = fields
                    .iter()
                    .map(|(fn_, fe)| format!(".{} = {}", sanitize_ident(fn_), self.expr_str(fe)))
                    .collect();
                format!("((struct {}){{{}}})", sanitize_ident(name), fs.join(", "))
            }
            Expr::Index { base, index } => {
                format!("({})[{}]", self.expr_str(base), self.expr_str(index))
            }
            Expr::ArrayLit(items) => {
                let els: Vec<String> = items.iter().map(|e| self.expr_str(e)).collect();
                // Compound literal of int64_t; caller must keep storage live.
                format!(
                    "((int64_t[]){{{}}})",
                    if els.is_empty() {
                        "0".into()
                    } else {
                        els.join(", ")
                    }
                )
            }
            Expr::Closure { .. } => "/* closure */((uint64_t)0)".into(),
        }
    }

    fn intrinsic_or_call(&self, name: &str, args: &[Expr]) -> String {
        let a = |i: usize| -> String {
            if i < args.len() {
                self.expr_str(&args[i])
            } else {
                "0".into()
            }
        };
        match name {
            "outb" => {
                let p = a(0);
                let v = a(1);
                format!(
                    "__extension__({{ __asm__ volatile(\"outb %0, %1\" : : \"a\"((uint8_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})"
                )
            }
            "inb" => {
                let p = a(0);
                format!(
                    "__extension__({{ uint8_t _v; __asm__ volatile(\"inb %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})"
                )
            }
            "outl" => {
                let p = a(0);
                let v = a(1);
                format!(
                    "__extension__({{ __asm__ volatile(\"outl %0, %1\" : : \"a\"((uint32_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})"
                )
            }
            "inl" => {
                let p = a(0);
                format!(
                    "__extension__({{ uint32_t _v; __asm__ volatile(\"inl %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})"
                )
            }
            "hlt" => "__extension__({ __asm__ volatile(\"hlt\" : : : \"memory\"); })".into(),
            "cli" => "__extension__({ __asm__ volatile(\"cli\" : : : \"memory\"); })".into(),
            "sti" => "__extension__({ __asm__ volatile(\"sti\" : : : \"memory\"); })".into(),
            "invlpg" => format!(
                "__extension__({{ __asm__ volatile(\"invlpg (%0)\" : : \"r\"({}) : \"memory\"); }})",
                a(0)
            ),
            "lidt" => format!(
                "__extension__({{ __asm__ volatile(\"lidt (%0)\" : : \"r\"({}) : \"memory\"); }})",
                a(0)
            ),
            "read_cr2" => {
                "__extension__({ uint64_t _v; __asm__ volatile(\"mov %%cr2, %0\" : \"=r\"(_v)); _v; })"
                    .into()
            }
            "load8" => format!("(*(volatile uint8_t*)({}))", a(0)),
            "load16" => format!("(*(volatile uint16_t*)({}))", a(0)),
            "load32" => format!("(*(volatile uint32_t*)({}))", a(0)),
            "load64" => format!("(*(volatile uint64_t*)({}))", a(0)),
            "store8" => format!(
                "__extension__({{ *(volatile uint8_t*)({}) = (uint8_t)({}); }})",
                a(0),
                a(1)
            ),
            "store16" => format!(
                "__extension__({{ *(volatile uint16_t*)({}) = (uint16_t)({}); }})",
                a(0),
                a(1)
            ),
            "store32" => format!(
                "__extension__({{ *(volatile uint32_t*)({}) = (uint32_t)({}); }})",
                a(0),
                a(1)
            ),
            "store64" => format!(
                "__extension__({{ *(volatile uint64_t*)({}) = (uint64_t)({}); }})",
                a(0),
                a(1)
            ),
            "invoke" if args.len() == 1 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(0))
            }
            "invoke" if args.len() == 2 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1))
            }
            "invoke" if args.len() == 3 => {
                format!(
                    "((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})",
                    a(0),
                    a(1),
                    a(2)
                )
            }
            "invoke1" if args.len() == 2 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1))
            }
            "invoke2" if args.len() == 3 => {
                format!(
                    "((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})",
                    a(0),
                    a(1),
                    a(2)
                )
            }
            _ => {
                let as_: Vec<String> = args.iter().map(|a| self.expr_str(a)).collect();
                format!("{}({})", sanitize_ident(name), as_.join(", "))
            }
        }
    }
}

fn emit_fn_def(ctx: &mut Ctx, name: &str, params: &[(String, Typ)], ret: &Typ, body: &[Stmt]) {
    let ps: Vec<String> = params
        .iter()
        .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
        .collect();
    let sec = if name == "kernel_entry" {
        " __attribute__((section(\".text.entry\")))"
    } else {
        ""
    };
    let attr = format!("__attribute__((used)){}", sec);
    let sig = format!(
        "{} {} {}({})",
        attr,
        ctype(ret),
        sanitize_ident(name),
        ps.join(", ")
    );
    ctx.push(&format!("{} {{", sig));
    ctx.indent();

    let mut locals: Vec<(String, String)> = Vec::new();
    collect_locals(body, &mut locals);
    for (n, ty) in &locals {
        ctx.push(&format!("{} {};", ty, n));
    }

    for stmt in body {
        emit_stmt(ctx, stmt);
    }
    if matches!(ret.canonical(), Typ::Void) {
        // avoid fallthrough warnings when body already returns
        if !body.last().is_some_and(|s| matches!(s, Stmt::Return(_))) {
            ctx.push("return;");
        }
    }

    ctx.dedent();
    ctx.line("}");
    ctx.line("");
}

fn emit_stmt(ctx: &mut Ctx, stmt: &Stmt) {
    match stmt {
        Stmt::Let(name, _, expr) => {
            ctx.push(&format!(
                "{} = {};",
                sanitize_ident(name),
                ctx.expr_str(expr)
            ));
        }
        Stmt::Assign(name, expr) => {
            ctx.push(&format!(
                "{} = {};",
                sanitize_ident(name),
                ctx.expr_str(expr)
            ));
        }
        Stmt::IndexAssign { base, index, value } => {
            ctx.push(&format!(
                "({})[{}] = {};",
                ctx.expr_str(base),
                ctx.expr_str(index),
                ctx.expr_str(value)
            ));
        }
        Stmt::FieldAssign { base, name, value } => {
            ctx.push(&format!(
                "({}).{} = {};",
                ctx.expr_str(base),
                sanitize_ident(name),
                ctx.expr_str(value)
            ));
        }
        Stmt::Return(e) => match e {
            Some(x) => ctx.push(&format!("return {};", ctx.expr_str(x))),
            None => ctx.push("return;"),
        },
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            ctx.push(&format!("if ({}) {{", ctx.expr_str(cond)));
            ctx.indent();
            for s in then_body {
                emit_stmt(ctx, s);
            }
            ctx.dedent();
            if !else_body.is_empty() {
                ctx.line("} else {");
                ctx.indent();
                for s in else_body {
                    emit_stmt(ctx, s);
                }
                ctx.dedent();
            }
            ctx.line("}");
        }
        Stmt::Loop { kind, cond, body } => {
            match kind {
                LoopKind::For { binding } => {
                    // Core IR for-loops only carry binding + optional cond; emit while form.
                    let _ = binding;
                    match cond {
                        Some(c) => ctx.push(&format!("while ({}) {{", ctx.expr_str(c))),
                        None => ctx.line("while (1) {"),
                    }
                }
                LoopKind::While | LoopKind::Infinite => match cond {
                    Some(c) => ctx.push(&format!("while ({}) {{", ctx.expr_str(c))),
                    None => ctx.line("while (1) {"),
                },
            }
            ctx.indent();
            for s in body {
                emit_stmt(ctx, s);
            }
            ctx.dedent();
            ctx.line("}");
        }
        Stmt::Match { scrutinee, arms } => {
            // Simple if/else chain; patterns are source text (Core IR stores pattern strings).
            let scr = ctx.expr_str(scrutinee);
            let mut first = true;
            for arm in arms {
                let cond = match_arm_cond(&scr, &arm.pattern);
                if first {
                    ctx.push(&format!("if ({}) {{", cond));
                    first = false;
                } else {
                    ctx.push(&format!("}} else if ({}) {{", cond));
                }
                ctx.indent();
                for s in &arm.body {
                    emit_stmt(ctx, s);
                }
                ctx.dedent();
            }
            if !first {
                ctx.line("}");
            }
        }
        Stmt::Throw(e) => {
            ctx.push(&format!(
                "/* throw */ (void)({}); return 0;",
                ctx.expr_str(e)
            ));
        }
        Stmt::Try { body, catches } => {
            ctx.line("/* try */ {");
            ctx.indent();
            for s in body {
                emit_stmt(ctx, s);
            }
            ctx.dedent();
            ctx.line("}");
            for c in catches {
                ctx.push(&format!("/* catch {} (not lowered) */", c.pattern));
            }
        }
        Stmt::Propagate => {
            ctx.line("/* propagate */");
        }
        Stmt::Expr(e) => {
            ctx.push(&format!("{};", ctx.expr_str(e)));
        }
        Stmt::Break => {
            ctx.line("break;");
        }
    }
}

fn match_arm_cond(scrutinee: &str, pattern: &str) -> String {
    let p = pattern.trim().trim_end_matches(':').trim();
    if p == "_" || p == "-" || p == "else" || p == "default" || p == ".." {
        return "1".into();
    }
    if p == "true" {
        return format!("({})", scrutinee);
    }
    if p == "false" {
        return format!("(!({}))", scrutinee);
    }
    if let Ok(n) = p.parse::<i64>() {
        return format!("(({}) == INT64_C({}))", scrutinee, n);
    }
    if p.len() >= 2 && p.starts_with('"') && p.ends_with('"') {
        let inner = &p[1..p.len() - 1];
        let escaped = inner.replace('\\', "\\\\").replace('"', "\\\"");
        return format!("(({}) == (const char*)\"{}\")", scrutinee, escaped);
    }
    // Ident binding / struct patterns: always true (lossy).
    "1".into()
}

fn collect_locals(stmts: &[Stmt], locals: &mut Vec<(String, String)>) {
    for stmt in stmts {
        match stmt {
            Stmt::Let(name, typ, _) => {
                let n = sanitize_ident(name);
                if !locals.iter().any(|(existing, _)| existing == &n) {
                    let ty = typ.as_ref().map(ctype).unwrap_or_else(|| "int64_t".into());
                    locals.push((n, ty));
                }
            }
            // Some fronts emit bare Assign without a prior Let.
            Stmt::Assign(name, _) => {
                let n = sanitize_ident(name);
                if !locals.iter().any(|(existing, _)| existing == &n) {
                    locals.push((n, "int64_t".into()));
                }
            }
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_locals(then_body, locals);
                collect_locals(else_body, locals);
            }
            Stmt::Loop { body, .. } => collect_locals(body, locals),
            Stmt::Match { arms, .. } => {
                for arm in arms {
                    collect_locals(&arm.body, locals);
                }
            }
            Stmt::Try { body, catches } => {
                collect_locals(body, locals);
                for c in catches {
                    collect_locals(&c.body, locals);
                }
            }
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core_ir::{CoreModuleIdentity, Expr, Stmt, Typ};

    #[test]
    fn emits_fib_style_function() {
        let module = UnifiedModule::with_identity(
            vec![Decl::Function {
                name: "fib".into(),
                params: vec![("n".into(), Typ::Int)],
                ret: Typ::Int,
                body: vec![
                    Stmt::If {
                        cond: Expr::Binary {
                            op: "le".into(),
                            lhs: Box::new(Expr::Ident("n".into())),
                            rhs: Box::new(Expr::IntLit(1)),
                        },
                        then_body: vec![Stmt::Return(Some(Expr::Ident("n".into())))],
                        else_body: vec![],
                    },
                    Stmt::Let("a".into(), Some(Typ::Int), Expr::IntLit(0)),
                    Stmt::Let("b".into(), Some(Typ::Int), Expr::IntLit(1)),
                    Stmt::Let("i".into(), Some(Typ::Int), Expr::IntLit(2)),
                    Stmt::Loop {
                        kind: LoopKind::While,
                        cond: Some(Expr::Binary {
                            op: "le".into(),
                            lhs: Box::new(Expr::Ident("i".into())),
                            rhs: Box::new(Expr::Ident("n".into())),
                        }),
                        body: vec![
                            Stmt::Let(
                                "t".into(),
                                Some(Typ::Int),
                                Expr::Binary {
                                    op: "add".into(),
                                    lhs: Box::new(Expr::Ident("a".into())),
                                    rhs: Box::new(Expr::Ident("b".into())),
                                },
                            ),
                            Stmt::Assign("a".into(), Expr::Ident("b".into())),
                            Stmt::Assign("b".into(), Expr::Ident("t".into())),
                            Stmt::Assign(
                                "i".into(),
                                Expr::Binary {
                                    op: "add".into(),
                                    lhs: Box::new(Expr::Ident("i".into())),
                                    rhs: Box::new(Expr::IntLit(1)),
                                },
                            ),
                        ],
                    },
                    Stmt::Return(Some(Expr::Ident("b".into()))),
                ],
                type_params: vec![],
            }],
            CoreModuleIdentity {
                package: Some("fib".into()),
                module: Some("fib.main".into()),
            },
        );
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("int64_t fib(int64_t n)"), "sig missing:\n{c}");
        assert!(c.contains("while"), "loop missing:\n{c}");
        assert!(c.contains("package: fib"), "identity missing:\n{c}");
        assert!(c.contains("__attribute__((used))"), "used attr:\n{c}");
    }

    #[test]
    fn emits_struct_and_field_assign() {
        let module = UnifiedModule::new(vec![
            Decl::Struct {
                name: "Point".into(),
                fields: vec![("x".into(), Typ::Int), ("y".into(), Typ::Int)],
                type_params: vec![],
            },
            Decl::Function {
                name: "bump".into(),
                params: vec![("p".into(), Typ::Named("Point".into()))],
                ret: Typ::Named("Point".into()),
                body: vec![
                    Stmt::FieldAssign {
                        base: Expr::Ident("p".into()),
                        name: "x".into(),
                        value: Expr::Binary {
                            op: "add".into(),
                            lhs: Box::new(Expr::Field {
                                base: Box::new(Expr::Ident("p".into())),
                                name: "x".into(),
                            }),
                            rhs: Box::new(Expr::IntLit(1)),
                        },
                    },
                    Stmt::Return(Some(Expr::Ident("p".into()))),
                ],
                type_params: vec![],
            },
        ]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("struct Point"), "struct:\n{c}");
        assert!(c.contains("(p).x ="), "field assign:\n{c}");
    }
}
