//! Core IR → C code emitter.
//!
//! Vlang-style C backend: emit portable C99, let GCC/Clang handle optimization.
//! Compile with: zig cc -c -target x86_64-freestanding -ffreestanding -O2 kernel.c

use crate::core_ir::{Decl, Expr, LoopKind, Stmt, Typ, UnifiedModule};

fn ctype(typ: &Typ) -> String {
    match typ.canonical() {
        Typ::Int => "int64_t".into(),
        Typ::Bool => "uint8_t".into(),
        Typ::Float => "double".into(),
        Typ::String => "const char*".into(),
        Typ::Void => "void".into(),
        Typ::Array(inner) => format!("{}*", ctype(&inner)),
        // Matches native lower: Vec = { ptr, len, cap } (8-byte fields).
        Typ::Vector(_) => "struct InVec".into(),
        Typ::Named(name) if name == "Vec" || name == "InVec" => "struct InVec".into(),
        Typ::Named(name) => format!("struct {}", sanitize_ident(&name)),
        Typ::Generic(_) => "int64_t".into(),
    }
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Emit a complete C translation unit from Core IR.
pub fn emit_c_module(module: &UnifiedModule) -> Result<String, String> {
    let mut func_names: Vec<String> = Vec::new();
    for decl in &module.decls {
        match decl {
            Decl::Function { name, .. } => func_names.push(name.clone()),
            Decl::Class { methods, .. } => {
                for m in methods {
                    if let Decl::Function { name, .. } = m {
                        func_names.push(name.clone());
                    }
                }
            }
            _ => {}
        }
    }
    let mut ctx = Ctx::new(func_names);

    ctx.line("/* Generated by Inauguration C backend */");
    ctx.line("#include <stdint.h>");
    ctx.line("#include <stddef.h>");
    ctx.line("");
    // Shared with native lower (ptr/len/cap, 8-byte fields).
    ctx.line("typedef struct InVec {");
    ctx.line("  int64_t *ptr;");
    ctx.line("  int64_t len;");
    ctx.line("  int64_t cap;");
    ctx.line("} InVec;");
    ctx.line("");

    if let Some(pkg) = &module.identity.package {
        ctx.push(&format!("/* package: {} */", pkg));
    }
    if let Some(mod_name) = &module.identity.module {
        ctx.push(&format!("/* module: {} */", mod_name));
    }
    if module.identity.package.is_some() || module.identity.module.is_some() {
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Struct { name, fields, .. } = decl {
            ctx.push(&format!("struct {} {{", sanitize_ident(name)));
            ctx.indent();
            if fields.is_empty() {
                ctx.push("char _pad;");
            } else {
                for (fname, ftype) in fields {
                    ctx.push(&format!("{} {};", ctype(ftype), sanitize_ident(fname)));
                }
            }
            ctx.dedent();
            ctx.line("};");
            ctx.line("");
        }
    }

    // Classes lower as structs + free methods (self first param).
    for decl in &module.decls {
        if let Decl::Class {
            name,
            fields,
            methods,
            ..
        } = decl
        {
            ctx.push(&format!("struct {} {{", sanitize_ident(name)));
            ctx.indent();
            if fields.is_empty() {
                ctx.push("char _pad;");
            } else {
                for (fname, ftype) in fields {
                    ctx.push(&format!("{} {};", ctype(ftype), sanitize_ident(fname)));
                }
            }
            ctx.dedent();
            ctx.line("};");
            ctx.line("");
            for m in methods {
                if let Decl::Function {
                    name: mname,
                    params,
                    ret,
                    body,
                    ..
                } = m
                {
                    let mut full_params = vec![("self".to_string(), Typ::Named(name.clone()))];
                    full_params.extend(params.iter().cloned());
                    emit_fn_def(
                        &mut ctx,
                        &format!("{}_{}", sanitize_ident(name), sanitize_ident(mname)),
                        &full_params,
                        ret,
                        body,
                    );
                }
            }
        }
    }

    for decl in &module.decls {
        if let Decl::Interface { name, methods, .. } = decl {
            ctx.push(&format!("/* interface {} */", sanitize_ident(name)));
            for m in methods {
                let ps: Vec<String> = m
                    .params
                    .iter()
                    .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                    .collect();
                ctx.push(&format!(
                    "/* {} {}({}); */",
                    ctype(&m.ret),
                    sanitize_ident(&m.name),
                    ps.join(", ")
                ));
            }
            ctx.line("");
        }
    }

    let has_globals = module
        .decls
        .iter()
        .any(|d| matches!(d, Decl::Global { .. }));
    if has_globals {
        for decl in &module.decls {
            if let Decl::Global {
                name, typ, init, ..
            } = decl
            {
                let init_s = match init {
                    Some(e) => format!(" = {}", ctx.expr_str(e)),
                    None => String::new(),
                };
                ctx.push(&format!(
                    "volatile {} {}{};",
                    ctype(typ),
                    sanitize_ident(name),
                    init_s
                ));
            }
        }
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Function {
            name, params, ret, ..
        } = decl
        {
            let ps: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                .collect();
            ctx.push(&format!(
                "{} {}({});",
                ctype(ret),
                sanitize_ident(name),
                ps.join(", ")
            ));
        }
    }
    if module
        .decls
        .iter()
        .any(|d| matches!(d, Decl::Function { .. }))
    {
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Function {
            name,
            params,
            ret,
            body,
            ..
        } = decl
        {
            emit_fn_def(&mut ctx, name, params, ret, body);
        }
    }

    for decl in &module.decls {
        if let Decl::Component {
            name,
            target,
            deterministic,
            ..
        } = decl
        {
            ctx.push(&format!(
                "/* component: {} target:{} deterministic:{} */",
                name, target, deterministic
            ));
        }
    }

    Ok(ctx.out)
}

struct Ctx {
    out: String,
    indent_lvl: u32,
    func_names: Vec<String>,
    /// Hoisted zero-capture closures emitted before the current function.
    hoisted: Vec<String>,
    tmp: u32,
    ret_is_void: bool,
}

impl Ctx {
    fn new(func_names: Vec<String>) -> Self {
        Self {
            out: String::new(),
            indent_lvl: 0,
            func_names,
            hoisted: Vec::new(),
            tmp: 0,
            ret_is_void: false,
        }
    }

    fn fresh(&mut self, prefix: &str) -> String {
        let id = self.tmp;
        self.tmp += 1;
        format!("__{}_{}", prefix, id)
    }

    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn push(&mut self, s: &str) {
        for _ in 0..self.indent_lvl {
            self.out.push_str("  ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn indent(&mut self) {
        self.indent_lvl += 1;
    }

    fn dedent(&mut self) {
        self.indent_lvl = self.indent_lvl.saturating_sub(1);
    }

    fn is_func(&self, name: &str) -> bool {
        self.func_names.iter().any(|n| n == name)
    }

    fn expr_str(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit(n) => format!("INT64_C({})", n),
            Expr::FloatLit(f) => {
                let bits = f.0;
                if bits.is_finite() {
                    format!("{:?}", bits)
                } else if bits.is_nan() {
                    "(0.0/0.0)".into()
                } else if bits.is_sign_negative() {
                    "(-1.0/0.0)".into()
                } else {
                    "(1.0/0.0)".into()
                }
            }
            Expr::BoolLit(b) => {
                if *b {
                    "1".into()
                } else {
                    "0".into()
                }
            }
            Expr::StringLit(s) => {
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
                format!("\"{}\"", escaped)
            }
            Expr::Ident(name) => {
                if self.is_func(name) {
                    format!("(uint64_t)({})", sanitize_ident(name))
                } else {
                    sanitize_ident(name)
                }
            }
            Expr::Binary { op, lhs, rhs } => {
                let (l, r) = (self.expr_str(lhs), self.expr_str(rhs));
                match op.as_str() {
                    "land" | "&&" => format!("({} && {})", l, r),
                    "lor" | "||" => format!("({} || {})", l, r),
                    "eq" | "==" => format!("({} == {})", l, r),
                    "neq" | "!=" => format!("({} != {})", l, r),
                    "lt" | "<" => format!("({} < {})", l, r),
                    "gt" | ">" => format!("({} > {})", l, r),
                    "le" | "<=" => format!("({} <= {})", l, r),
                    "ge" | ">=" => format!("({} >= {})", l, r),
                    "add" | "+" => format!("({} + {})", l, r),
                    "sub" | "-" => format!("({} - {})", l, r),
                    "mul" | "*" => format!("({} * {})", l, r),
                    "div" | "/" => format!("({} / {})", l, r),
                    "mod" | "%" => format!("({} % {})", l, r),
                    "band" | "&" => format!("({} & {})", l, r),
                    "bor" | "|" => format!("({} | {})", l, r),
                    "xor" | "^" => format!("({} ^ {})", l, r),
                    "shl" | "<<" => format!("({} << {})", l, r),
                    "shr" | ">>" => format!("({} >> {})", l, r),
                    _ => format!("({} /*op:{}*/ {})", l, op, r),
                }
            }
            Expr::Unary { op, expr } => {
                let e = self.expr_str(expr);
                match op.as_str() {
                    "neg" | "-" => format!("(-{})", e),
                    "not" | "!" => format!("(!{})", e),
                    "bnot" | "~" => format!("(~{})", e),
                    _ => format!("(/*op:{}*/{})", op, e),
                }
            }
            Expr::Call { callee, args } => {
                // method call: recv.method(args) → method(recv, args…)
                if let Expr::Field { base, name } = &**callee {
                    let mut as_ = vec![self.expr_str(base)];
                    as_.extend(args.iter().map(|a| self.expr_str(a)));
                    return format!("{}({})", sanitize_ident(name), as_.join(", "));
                }
                if let Expr::Ident(name) = &**callee {
                    self.intrinsic_or_call(name, args)
                } else {
                    let callee_s = self.expr_str(callee);
                    let as_: Vec<String> = args.iter().map(|a| self.expr_str(a)).collect();
                    format!("(({})({}))", callee_s, as_.join(", "))
                }
            }
            Expr::Field { base, name } => {
                format!("({}).{}", self.expr_str(base), sanitize_ident(name))
            }
            Expr::StructInit { name, fields } => {
                let fs: Vec<String> = fields
                    .iter()
                    .map(|(fn_, fe)| format!(".{} = {}", sanitize_ident(fn_), self.expr_str(fe)))
                    .collect();
                format!("((struct {}){{{}}})", sanitize_ident(name), fs.join(", "))
            }
            Expr::Index { base, index } => {
                format!("({})[{}]", self.expr_str(base), self.expr_str(index))
            }
            Expr::ArrayLit(items) => {
                let els: Vec<String> = items.iter().map(|e| self.expr_str(e)).collect();
                // Compound literal of int64_t; caller must keep storage live.
                format!(
                    "((int64_t[]){{{}}})",
                    if els.is_empty() {
                        "0".into()
                    } else {
                        els.join(", ")
                    }
                )
            }
            Expr::Closure {
                params,
                ret,
                body,
                captures,
            } => {
                let cname = self.fresh("closure");
                let env_name = format!("{}_env", cname);
                let mut helper = String::new();
                if !captures.is_empty() {
                    helper.push_str(&format!("struct {} {{\n", env_name));
                    for cap in captures {
                        helper.push_str(&format!("  int64_t {};\n", sanitize_ident(cap)));
                    }
                    helper.push_str("};\n");
                }
                let mut ps: Vec<String> = params
                    .iter()
                    .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                    .collect();
                if !captures.is_empty() {
                    ps.insert(0, format!("struct {} *env", env_name));
                }
                helper.push_str(&format!(
                    "static {} {}({}) {{\n",
                    ctype(ret),
                    cname,
                    ps.join(", ")
                ));
                let mut nested = Ctx::new(self.func_names.clone());
                nested.ret_is_void = matches!(ret.canonical(), Typ::Void);
                nested.indent_lvl = 1;
                for cap in captures {
                    let n = sanitize_ident(cap);
                    nested.push(&format!("int64_t {} = env->{};", n, n));
                }
                let mut locals = Vec::new();
                collect_locals(body, &mut locals);
                for (n, ty) in &locals {
                    if captures.iter().any(|c| sanitize_ident(c) == *n) {
                        continue;
                    }
                    nested.push(&format!("{} {};", ty, n));
                }
                for s in body {
                    emit_stmt(&mut nested, s);
                }
                if nested.ret_is_void && !body.last().is_some_and(|s| matches!(s, Stmt::Return(_)))
                {
                    nested.push("return;");
                }
                helper.push_str(&nested.out);
                helper.push_str("}\n");
                self.hoisted.push(helper);
                if captures.is_empty() {
                    format!("(uint64_t)({})", cname)
                } else {
                    let env_var = self.fresh("env");
                    let fields: Vec<String> = captures
                        .iter()
                        .map(|cap| {
                            let n = sanitize_ident(cap);
                            format!(".{} = {}", n, n)
                        })
                        .collect();
                    format!(
                        "({{ struct {env} {var} = {{ {fields} }}; (uint64_t)({fn}); }})",
                        env = env_name,
                        var = env_var,
                        fields = fields.join(", "),
                        fn = cname,
                    )
                }
            }
        }
    }

    fn intrinsic_or_call(&mut self, name: &str, args: &[Expr]) -> String {
        let evaled: Vec<String> = args.iter().map(|e| self.expr_str(e)).collect();
        let a = |i: usize| -> String { evaled.get(i).cloned().unwrap_or_else(|| "0".into()) };
        match name {
            "outb" => {
                let p = a(0);
                let v = a(1);
                format!(
                    "__extension__({{ __asm__ volatile(\"outb %0, %1\" : : \"a\"((uint8_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})"
                )
            }
            "inb" => {
                let p = a(0);
                format!(
                    "__extension__({{ uint8_t _v; __asm__ volatile(\"inb %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})"
                )
            }
            "outl" => {
                let p = a(0);
                let v = a(1);
                format!(
                    "__extension__({{ __asm__ volatile(\"outl %0, %1\" : : \"a\"((uint32_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})"
                )
            }
            "inl" => {
                let p = a(0);
                format!(
                    "__extension__({{ uint32_t _v; __asm__ volatile(\"inl %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})"
                )
            }
            "hlt" => "__extension__({ __asm__ volatile(\"hlt\" : : : \"memory\"); })".into(),
            "cli" => "__extension__({ __asm__ volatile(\"cli\" : : : \"memory\"); })".into(),
            "sti" => "__extension__({ __asm__ volatile(\"sti\" : : : \"memory\"); })".into(),
            "invlpg" => format!(
                "__extension__({{ __asm__ volatile(\"invlpg (%0)\" : : \"r\"({}) : \"memory\"); }})",
                a(0)
            ),
            "lidt" => format!(
                "__extension__({{ __asm__ volatile(\"lidt (%0)\" : : \"r\"({}) : \"memory\"); }})",
                a(0)
            ),
            "read_cr2" => {
                "__extension__({ uint64_t _v; __asm__ volatile(\"mov %%cr2, %0\" : \"=r\"(_v)); _v; })"
                    .into()
            }
            "load8" => format!("(*(volatile uint8_t*)({}))", a(0)),
            "load16" => format!("(*(volatile uint16_t*)({}))", a(0)),
            "load32" => format!("(*(volatile uint32_t*)({}))", a(0)),
            "load64" => format!("(*(volatile uint64_t*)({}))", a(0)),
            "store8" => format!(
                "__extension__({{ *(volatile uint8_t*)({}) = (uint8_t)({}); }})",
                a(0),
                a(1)
            ),
            "store16" => format!(
                "__extension__({{ *(volatile uint16_t*)({}) = (uint16_t)({}); }})",
                a(0),
                a(1)
            ),
            "store32" => format!(
                "__extension__({{ *(volatile uint32_t*)({}) = (uint32_t)({}); }})",
                a(0),
                a(1)
            ),
            "store64" => format!(
                "__extension__({{ *(volatile uint64_t*)({}) = (uint64_t)({}); }})",
                a(0),
                a(1)
            ),
            "invoke" if args.len() == 1 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(0))
            }
            "invoke" if args.len() == 2 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1))
            }
            "invoke" if args.len() == 3 => {
                format!(
                    "((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})",
                    a(0),
                    a(1),
                    a(2)
                )
            }
            "invoke1" if args.len() == 2 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1))
            }
            "invoke2" if args.len() == 3 => {
                format!(
                    "((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})",
                    a(0),
                    a(1),
                    a(2)
                )
            }
            _ => {
                let as_: Vec<String> = args.iter().map(|a| self.expr_str(a)).collect();
                format!("{}({})", sanitize_ident(name), as_.join(", "))
            }
        }
    }
}

fn emit_fn_def(ctx: &mut Ctx, name: &str, params: &[(String, Typ)], ret: &Typ, body: &[Stmt]) {
    let ps: Vec<String> = params
        .iter()
        .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
        .collect();
    let sec = if name == "kernel_entry" {
        " __attribute__((section(\".text.entry\")))"
    } else {
        ""
    };
    let attr = format!("__attribute__((used)){}", sec);
    let sig = format!(
        "{} {} {}({})",
        attr,
        ctype(ret),
        sanitize_ident(name),
        ps.join(", ")
    );

    // Build body into a nested buffer so hoisted closures land before the fn.
    let mut body_ctx = Ctx::new(ctx.func_names.clone());
    body_ctx.tmp = ctx.tmp;
    body_ctx.ret_is_void = matches!(ret.canonical(), Typ::Void);
    body_ctx.indent_lvl = 1;

    let mut locals: Vec<(String, String)> = Vec::new();
    collect_locals(body, &mut locals);
    // iterator / match temps
    collect_loop_bindings(body, &mut locals);
    for (n, ty) in &locals {
        body_ctx.push(&format!("{} {};", ty, n));
    }
    // runtime error flag for throw/try/propagate (function-local, simple model)
    body_ctx.push("int __in_err = 0;");
    body_ctx.push("int64_t __in_err_val = 0;");

    for stmt in body {
        emit_stmt(&mut body_ctx, stmt);
    }
    if body_ctx.ret_is_void && !body.last().is_some_and(|s| matches!(s, Stmt::Return(_))) {
        body_ctx.push("return;");
    }

    ctx.tmp = body_ctx.tmp;
    for h in body_ctx.hoisted.drain(..) {
        ctx.out.push_str(&h);
        ctx.out.push('\n');
    }

    ctx.push(&format!("{} {{", sig));
    ctx.out.push_str(&body_ctx.out);
    ctx.line("}");
    ctx.line("");
}

fn emit_stmt(ctx: &mut Ctx, stmt: &Stmt) {
    match stmt {
        Stmt::Let(name, _, expr) => {
            let rhs = ctx.expr_str(expr);
            ctx.push(&format!("{} = {};", sanitize_ident(name), rhs));
        }
        Stmt::Assign(name, expr) => {
            let rhs = ctx.expr_str(expr);
            ctx.push(&format!("{} = {};", sanitize_ident(name), rhs));
        }
        Stmt::IndexAssign { base, index, value } => {
            let b = ctx.expr_str(base);
            let i = ctx.expr_str(index);
            let v = ctx.expr_str(value);
            ctx.push(&format!("({})[{}] = {};", b, i, v));
        }
        Stmt::FieldAssign { base, name, value } => {
            let b = ctx.expr_str(base);
            let v = ctx.expr_str(value);
            ctx.push(&format!("({}).{} = {};", b, sanitize_ident(name), v));
        }
        Stmt::Return(e) => match e {
            Some(x) => {
                let v = ctx.expr_str(x);
                ctx.push(&format!("return {};", v));
            }
            None => ctx.push("return;"),
        },
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            let c = ctx.expr_str(cond);
            ctx.push(&format!("if ({}) {{", c));
            ctx.indent();
            for s in then_body {
                emit_stmt(ctx, s);
            }
            ctx.dedent();
            if !else_body.is_empty() {
                ctx.line("} else {");
                ctx.indent();
                for s in else_body {
                    emit_stmt(ctx, s);
                }
                ctx.dedent();
            }
            ctx.line("}");
        }
        Stmt::Loop { kind, cond, body } => {
            match kind {
                LoopKind::For { binding } => {
                    // cond = iterable. Prefer InVec {ptr,len} layout from native lower.
                    let iter = cond
                        .as_ref()
                        .map(|c| ctx.expr_str(c))
                        .unwrap_or_else(|| "((struct InVec){0})".into());
                    let idx = ctx.fresh("i");
                    let len = ctx.fresh("len");
                    let ptr = ctx.fresh("ptr");
                    let vec = ctx.fresh("vec");
                    let bind = sanitize_ident(binding.trim().trim_start_matches("& "));
                    ctx.push(&format!("struct InVec {} = {};", vec, iter));
                    ctx.push(&format!("int64_t* {} = (int64_t*)({}.ptr);", ptr, vec));
                    ctx.push(&format!("int64_t {} = {}.len;", len, vec));
                    ctx.push(&format!(
                        "for (int64_t {} = 0; {} < {}; {}++) {{",
                        idx, idx, len, idx
                    ));
                    ctx.indent();
                    if bind != "_" && !bind.is_empty() {
                        ctx.push(&format!("{} = {}[{}];", bind, ptr, idx));
                    }
                    for s in body {
                        emit_stmt(ctx, s);
                    }
                    ctx.dedent();
                    ctx.line("}");
                }
                LoopKind::While | LoopKind::Infinite => {
                    match cond {
                        Some(c) => {
                            let cstr = ctx.expr_str(c);
                            ctx.push(&format!("while ({}) {{", cstr));
                        }
                        None => ctx.line("while (1) {"),
                    }
                    ctx.indent();
                    for s in body {
                        emit_stmt(ctx, s);
                    }
                    ctx.dedent();
                    ctx.line("}");
                }
            }
        }
        Stmt::Match { scrutinee, arms } => {
            // Simple if/else chain; patterns are source text (Core IR stores pattern strings).
            let scr_tmp = ctx.fresh("scr");
            let scr = ctx.expr_str(scrutinee);
            ctx.push(&format!("int64_t {} = (int64_t)({});", scr_tmp, scr));
            let mut first = true;
            for arm in arms {
                let (cond, binds) = match_arm_cond_and_binds(&scr_tmp, &arm.pattern);
                if first {
                    ctx.push(&format!("if ({}) {{", cond));
                    first = false;
                } else {
                    ctx.push(&format!("}} else if ({}) {{", cond));
                }
                ctx.indent();
                for b in binds {
                    ctx.push(&b);
                }
                for s in &arm.body {
                    emit_stmt(ctx, s);
                }
                ctx.dedent();
            }
            if !first {
                ctx.line("}");
            }
        }
        Stmt::Throw(e) => {
            let val = ctx.expr_str(e);
            ctx.push(&format!("__in_err = 1; __in_err_val = (int64_t)({});", val));
            if ctx.ret_is_void {
                ctx.push("return;");
            } else {
                ctx.push("return 0;");
            }
        }
        Stmt::Try { body, catches } => {
            ctx.line("{ /* try */");
            ctx.indent();
            ctx.push("int __in_err_save = __in_err;");
            ctx.push("__in_err = 0;");
            for s in body {
                emit_stmt(ctx, s);
            }
            if !catches.is_empty() {
                ctx.push("if (__in_err) {");
                ctx.indent();
                for (i, c) in catches.iter().enumerate() {
                    let bind = c.pattern.trim();
                    let (cond, binds) = match_arm_cond_and_binds("__in_err_val", bind);
                    if i == 0 {
                        ctx.push(&format!("if ({}) {{", cond));
                    } else {
                        ctx.push(&format!("}} else if ({}) {{", cond));
                    }
                    ctx.indent();
                    for b in binds {
                        ctx.push(&b);
                    }
                    for s in &c.body {
                        emit_stmt(ctx, s);
                    }
                    ctx.push("__in_err = 0;");
                    ctx.dedent();
                }
                ctx.line("}"); // last else-if arm
                ctx.dedent();
                ctx.line("}");
            }
            ctx.push("if (!__in_err) { __in_err = __in_err_save; }");
            ctx.dedent();
            ctx.line("}");
        }
        Stmt::Propagate => {
            ctx.push("if (__in_err) {");
            ctx.indent();
            if ctx.ret_is_void {
                ctx.push("return;");
            } else {
                ctx.push("return __in_err_val;");
            }
            ctx.dedent();
            ctx.line("}");
        }
        Stmt::Expr(e) => {
            let v = ctx.expr_str(e);
            ctx.push(&format!("{};", v));
        }
        Stmt::Break => {
            ctx.line("break;");
        }
    }
}

fn is_simple_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// Returns (C condition, binding statements) for a match arm pattern string.
fn match_arm_cond_and_binds(scrutinee: &str, pattern: &str) -> (String, Vec<String>) {
    let p = pattern.trim().trim_end_matches(':').trim();
    if p == "_" || p == "-" || p == "else" || p == "default" || p == ".." {
        return ("1".into(), vec![]);
    }
    if p == "true" {
        return (format!("({})", scrutinee), vec![]);
    }
    if p == "false" {
        return (format!("(!({}))", scrutinee), vec![]);
    }
    if let Ok(n) = p.parse::<i64>() {
        return (format!("(({}) == INT64_C({}))", scrutinee, n), vec![]);
    }
    if p.len() >= 2 && p.starts_with('"') && p.ends_with('"') {
        let inner = &p[1..p.len() - 1];
        let escaped = inner.replace('\\', "\\\\").replace('"', "\\\"");
        return (
            format!("(({}) == (const char*)\"{}\")", scrutinee, escaped),
            vec![],
        );
    }
    // Ident binding: always matches, bind name = scrutinee.
    if is_simple_ident(p) {
        let name = sanitize_ident(p);
        return (
            "1".into(),
            vec![format!("int64_t {} = {};", name, scrutinee)],
        );
    }
    // Struct / other patterns: always true (lossy).
    ("1".into(), vec![])
}

fn collect_loop_bindings(stmts: &[Stmt], locals: &mut Vec<(String, String)>) {
    for stmt in stmts {
        match stmt {
            Stmt::Loop {
                kind: LoopKind::For { binding },
                body,
                ..
            } => {
                let bind = sanitize_ident(binding.trim().trim_start_matches("& "));
                if bind != "_" && !bind.is_empty() && !locals.iter().any(|(n, _)| n == &bind) {
                    locals.push((bind, "int64_t".into()));
                }
                collect_loop_bindings(body, locals);
            }
            Stmt::Loop { body, .. } => collect_loop_bindings(body, locals),
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_loop_bindings(then_body, locals);
                collect_loop_bindings(else_body, locals);
            }
            Stmt::Match { arms, .. } => {
                for arm in arms {
                    collect_loop_bindings(&arm.body, locals);
                }
            }
            Stmt::Try { body, catches } => {
                collect_loop_bindings(body, locals);
                for c in catches {
                    collect_loop_bindings(&c.body, locals);
                }
            }
            _ => {}
        }
    }
}

fn collect_locals(stmts: &[Stmt], locals: &mut Vec<(String, String)>) {
    for stmt in stmts {
        match stmt {
            Stmt::Let(name, typ, _) => {
                let n = sanitize_ident(name);
                if !locals.iter().any(|(existing, _)| existing == &n) {
                    let ty = typ.as_ref().map(ctype).unwrap_or_else(|| "int64_t".into());
                    locals.push((n, ty));
                }
            }
            // Some fronts emit bare Assign without a prior Let.
            Stmt::Assign(name, _) => {
                let n = sanitize_ident(name);
                if !locals.iter().any(|(existing, _)| existing == &n) {
                    locals.push((n, "int64_t".into()));
                }
            }
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_locals(then_body, locals);
                collect_locals(else_body, locals);
            }
            Stmt::Loop { body, .. } => collect_locals(body, locals),
            Stmt::Match { arms, .. } => {
                for arm in arms {
                    collect_locals(&arm.body, locals);
                }
            }
            Stmt::Try { body, catches } => {
                collect_locals(body, locals);
                for c in catches {
                    collect_locals(&c.body, locals);
                }
            }
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core_ir::{CoreModuleIdentity, Expr, Stmt, Typ};

    #[test]
    fn emits_fib_style_function() {
        let module = UnifiedModule::with_identity(
            vec![Decl::Function {
                name: "fib".into(),
                params: vec![("n".into(), Typ::Int)],
                ret: Typ::Int,
                body: vec![
                    Stmt::If {
                        cond: Expr::Binary {
                            op: "le".into(),
                            lhs: Box::new(Expr::Ident("n".into())),
                            rhs: Box::new(Expr::IntLit(1)),
                        },
                        then_body: vec![Stmt::Return(Some(Expr::Ident("n".into())))],
                        else_body: vec![],
                    },
                    Stmt::Let("a".into(), Some(Typ::Int), Expr::IntLit(0)),
                    Stmt::Let("b".into(), Some(Typ::Int), Expr::IntLit(1)),
                    Stmt::Let("i".into(), Some(Typ::Int), Expr::IntLit(2)),
                    Stmt::Loop {
                        kind: LoopKind::While,
                        cond: Some(Expr::Binary {
                            op: "le".into(),
                            lhs: Box::new(Expr::Ident("i".into())),
                            rhs: Box::new(Expr::Ident("n".into())),
                        }),
                        body: vec![
                            Stmt::Let(
                                "t".into(),
                                Some(Typ::Int),
                                Expr::Binary {
                                    op: "add".into(),
                                    lhs: Box::new(Expr::Ident("a".into())),
                                    rhs: Box::new(Expr::Ident("b".into())),
                                },
                            ),
                            Stmt::Assign("a".into(), Expr::Ident("b".into())),
                            Stmt::Assign("b".into(), Expr::Ident("t".into())),
                            Stmt::Assign(
                                "i".into(),
                                Expr::Binary {
                                    op: "add".into(),
                                    lhs: Box::new(Expr::Ident("i".into())),
                                    rhs: Box::new(Expr::IntLit(1)),
                                },
                            ),
                        ],
                    },
                    Stmt::Return(Some(Expr::Ident("b".into()))),
                ],
                type_params: vec![],
            }],
            CoreModuleIdentity {
                package: Some("fib".into()),
                module: Some("fib.main".into()),
            },
        );
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("int64_t fib(int64_t n)"), "sig missing:\n{c}");
        assert!(c.contains("while"), "loop missing:\n{c}");
        assert!(c.contains("package: fib"), "identity missing:\n{c}");
        assert!(c.contains("__attribute__((used))"), "used attr:\n{c}");
    }

    #[test]
    fn emits_struct_and_field_assign() {
        let module = UnifiedModule::new(vec![
            Decl::Struct {
                name: "Point".into(),
                fields: vec![("x".into(), Typ::Int), ("y".into(), Typ::Int)],
                type_params: vec![],
            },
            Decl::Function {
                name: "bump".into(),
                params: vec![("p".into(), Typ::Named("Point".into()))],
                ret: Typ::Named("Point".into()),
                body: vec![
                    Stmt::FieldAssign {
                        base: Expr::Ident("p".into()),
                        name: "x".into(),
                        value: Expr::Binary {
                            op: "add".into(),
                            lhs: Box::new(Expr::Field {
                                base: Box::new(Expr::Ident("p".into())),
                                name: "x".into(),
                            }),
                            rhs: Box::new(Expr::IntLit(1)),
                        },
                    },
                    Stmt::Return(Some(Expr::Ident("p".into()))),
                ],
                type_params: vec![],
            },
        ]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("struct Point"), "struct:\n{c}");
        assert!(c.contains("(p).x ="), "field assign:\n{c}");
    }

    #[test]
    fn emits_method_call_as_free_fn() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "run".into(),
            params: vec![("c".into(), Typ::Named("Calc".into()))],
            ret: Typ::Int,
            body: vec![Stmt::Return(Some(Expr::Call {
                callee: Box::new(Expr::Field {
                    base: Box::new(Expr::Ident("c".into())),
                    name: "add".into(),
                }),
                args: vec![Expr::IntLit(3)],
            }))],
            type_params: vec![],
        }]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("add(c, INT64_C(3))"), "method call:\n{c}");
    }

    #[test]
    fn emits_match_int_arms() {
        use crate::core_ir::MatchArm;
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "classify".into(),
            params: vec![("x".into(), Typ::Int)],
            ret: Typ::Int,
            body: vec![Stmt::Match {
                scrutinee: Expr::Ident("x".into()),
                arms: vec![
                    MatchArm {
                        pattern: "0".into(),
                        body: vec![Stmt::Return(Some(Expr::IntLit(1)))],
                    },
                    MatchArm {
                        pattern: "_".into(),
                        body: vec![Stmt::Return(Some(Expr::IntLit(2)))],
                    },
                ],
            }],
            type_params: vec![],
        }]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("== INT64_C(0)"), "match arm:\n{c}");
        assert!(c.contains("else if"), "else if chain:\n{c}");
    }

    #[test]
    fn emits_try_throw_propagate() {
        use crate::core_ir::CatchArm;
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "risky".into(),
            params: vec![],
            ret: Typ::Int,
            body: vec![
                Stmt::Try {
                    body: vec![Stmt::Throw(Expr::IntLit(9))],
                    catches: vec![CatchArm {
                        pattern: "e".into(),
                        body: vec![Stmt::Return(Some(Expr::Ident("e".into())))],
                    }],
                },
                Stmt::Propagate,
                Stmt::Return(Some(Expr::IntLit(0))),
            ],
            type_params: vec![],
        }]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("__in_err"), "err flag:\n{c}");
        assert!(c.contains("/* try */"), "try block:\n{c}");
        assert!(c.contains("return __in_err_val"), "propagate:\n{c}");
    }

    #[test]
    fn emits_for_in_index_walk() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "sum".into(),
            params: vec![("xs".into(), Typ::Named("Vec".into()))],
            ret: Typ::Int,
            body: vec![
                Stmt::Let("acc".into(), Some(Typ::Int), Expr::IntLit(0)),
                Stmt::Loop {
                    kind: LoopKind::For {
                        binding: "v".into(),
                    },
                    cond: Some(Expr::Ident("xs".into())),
                    body: vec![Stmt::Assign(
                        "acc".into(),
                        Expr::Binary {
                            op: "add".into(),
                            lhs: Box::new(Expr::Ident("acc".into())),
                            rhs: Box::new(Expr::Ident("v".into())),
                        },
                    )],
                },
                Stmt::Return(Some(Expr::Ident("acc".into()))),
            ],
            type_params: vec![],
        }]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("struct InVec"), "InVec typedef/use:\n{c}");
        assert!(c.contains(".ptr"), "vec.ptr:\n{c}");
        assert!(c.contains(".len"), "vec.len:\n{c}");
        assert!(c.contains("for (int64_t"), "for loop:\n{c}");
        assert!(c.contains("int64_t v;"), "binding local:\n{c}");
    }

    #[test]
    fn hoists_zero_capture_closure() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "main".into(),
            params: vec![],
            ret: Typ::Int,
            body: vec![
                Stmt::Let(
                    "f".into(),
                    None,
                    Expr::Closure {
                        params: vec![("x".into(), Typ::Int)],
                        ret: Typ::Int,
                        body: vec![Stmt::Return(Some(Expr::Ident("x".into())))],
                        captures: vec![],
                    },
                ),
                Stmt::Return(Some(Expr::Ident("f".into()))),
            ],
            type_params: vec![],
        }]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("static int64_t __closure_"), "hoisted:\n{c}");
        assert!(c.contains("(uint64_t)(__closure_"), "fn ptr:\n{c}");
    }

    fn write_temp(name: &str, src: &str) -> std::path::PathBuf {
        use std::time::{SystemTime, UNIX_EPOCH};
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        let dir = std::env::temp_dir().join(format!(
            "inauguration-c-emit-{}-{}-{}",
            std::process::id(),
            unique,
            name
        ));
        std::fs::create_dir_all(&dir).expect("mkdir");
        let path = dir.join(name);
        std::fs::write(&path, src).expect("write");
        path
    }

    #[test]
    fn polyglot_in_control_flow_emits_if_while() {
        let path = write_temp(
            "control_flow.in",
            r#"fn helper(value: Int) -> Int { return value; }
fn main() -> Int {
  let value: Int = 1;
  value = value + 2;
  helper(value);
  if value > 2 { value = value - 1; } else { value = 0; }
  while value < 4 { value = value + 1; }
  return value;
}
"#,
        );
        let module = crate::in_lang_parse::parse_in_file(&path).expect("parse .in");
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("int64_t helper(int64_t value)"), "helper:\n{c}");
        assert!(c.contains("while"), "while:\n{c}");
        assert!(c.contains("if ("), "if:\n{c}");
        let _ = std::fs::remove_dir_all(path.parent().unwrap());
    }

    #[test]
    fn polyglot_c_and_go_answer_main() {
        use crate::parser_registry::ParserId;
        let c_path = write_temp(
            "sample.c",
            "int answer(void) { return 42; }\nint main(void) { return 0; }\n",
        );
        let go_path = write_temp(
            "sample.go",
            "package main\nfunc answer() int { return 42 }\nfunc main() {}\n",
        );
        let c_mod = crate::compiler::tree_front::parse_polyglot_file(ParserId::C, &c_path)
            .expect("parse c");
        let go_mod = crate::compiler::tree_front::parse_polyglot_file(ParserId::Go, &go_path)
            .expect("parse go");
        let c_out = emit_c_module(&c_mod).expect("emit c");
        let go_out = emit_c_module(&go_mod).expect("emit go");
        assert!(c_out.contains("int64_t answer()"), "c answer:\n{c_out}");
        assert!(c_out.contains("return INT64_C(42)"), "c lit:\n{c_out}");
        assert!(go_out.contains("int64_t answer()"), "go answer:\n{go_out}");
        assert!(go_out.contains("return INT64_C(42)"), "go lit:\n{go_out}");
        let _ = std::fs::remove_dir_all(c_path.parent().unwrap());
        let _ = std::fs::remove_dir_all(go_path.parent().unwrap());
    }

    #[test]
    fn polyglot_icore_min_assigns_local() {
        let path = write_temp(
            "min.icore",
            r#"{
  "icoreVersion": 2,
  "decls": [
    {"kind": "function", "name": "helper", "params": [], "return": "Int",
     "body": [{"kind": "return", "value": 7}]},
    {"kind": "function", "name": "main", "params": [], "return": "Void",
     "body": [
       {"kind": "assign", "target": "value",
        "value": {"kind": "call", "callee": "helper"}},
       {"kind": "return"}
     ]}
  ]
}
"#,
        );
        let module = crate::compiler::icore::parse_icore_file(&path).expect("parse icore");
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("int64_t value;"), "local:\n{c}");
        assert!(c.contains("value = helper()"), "assign:\n{c}");
        let _ = std::fs::remove_dir_all(path.parent().unwrap());
    }

    #[test]
    fn emits_multi_catch_chain() {
        use crate::core_ir::CatchArm;
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "risky".into(),
            params: vec![],
            ret: Typ::Int,
            body: vec![Stmt::Try {
                body: vec![Stmt::Throw(Expr::IntLit(1))],
                catches: vec![
                    CatchArm {
                        pattern: "0".into(),
                        body: vec![Stmt::Return(Some(Expr::IntLit(10)))],
                    },
                    CatchArm {
                        pattern: "e".into(),
                        body: vec![Stmt::Return(Some(Expr::Ident("e".into())))],
                    },
                ],
            }],
            type_params: vec![],
        }]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("else if"), "multi-catch:\n{c}");
        assert!(c.contains("== INT64_C(0)"), "int catch:\n{c}");
    }

    #[test]
    fn hoists_capturing_closure_env() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "main".into(),
            params: vec![],
            ret: Typ::Int,
            body: vec![
                Stmt::Let("y".into(), Some(Typ::Int), Expr::IntLit(7)),
                Stmt::Let(
                    "f".into(),
                    None,
                    Expr::Closure {
                        params: vec![("x".into(), Typ::Int)],
                        ret: Typ::Int,
                        body: vec![Stmt::Return(Some(Expr::Binary {
                            op: "add".into(),
                            lhs: Box::new(Expr::Ident("x".into())),
                            rhs: Box::new(Expr::Ident("y".into())),
                        }))],
                        captures: vec!["y".into()],
                    },
                ),
                Stmt::Return(Some(Expr::Ident("f".into()))),
            ],
            type_params: vec![],
        }]);
        let c = emit_c_module(&module).expect("emit");
        assert!(c.contains("_env"), "env struct:\n{c}");
        assert!(c.contains("env->y"), "env load:\n{c}");
        assert!(c.contains(".y = y"), "env init:\n{c}");
    }
}
