//! Core IR → high-level source sinks (Go, Rust).
//!
//! Lossy subset printers: functions, structs, control flow, calls.
//! Not a full project/crate generator.

use crate::core_ir::{Decl, Expr, LoopKind, Stmt, Typ, UnifiedModule};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceLang {
    Go,
    Rust,
}

impl SourceLang {
    pub fn extension(self) -> &'static str {
        match self {
            SourceLang::Go => "go",
            SourceLang::Rust => "rs",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            SourceLang::Go => "go",
            SourceLang::Rust => "rust",
        }
    }
}

pub fn emit_source_module(module: &UnifiedModule, lang: SourceLang) -> Result<String, String> {
    match lang {
        SourceLang::Go => emit_go(module),
        SourceLang::Rust => emit_rust(module),
    }
}

fn go_type(typ: &Typ) -> String {
    match typ.canonical() {
        Typ::Int => "int64".into(),
        Typ::Bool => "bool".into(),
        Typ::Float => "float64".into(),
        Typ::String => "string".into(),
        Typ::Void => "".into(),
        Typ::Array(inner) | Typ::Vector(inner) => format!("[]{}", go_type(&inner)),
        Typ::Named(n) if n == "Vec" || n == "InVec" => "[]int64".into(),
        Typ::Named(n) => sanitize(&n),
        Typ::Generic(n) => sanitize(&n),
    }
}

fn rust_type(typ: &Typ) -> String {
    match typ.canonical() {
        Typ::Int => "i64".into(),
        Typ::Bool => "bool".into(),
        Typ::Float => "f64".into(),
        Typ::String => "String".into(),
        Typ::Void => "()".into(),
        Typ::Array(inner) | Typ::Vector(inner) => format!("Vec<{}>", rust_type(&inner)),
        Typ::Named(n) if n == "Vec" || n == "InVec" => "Vec<i64>".into(),
        Typ::Named(n) => sanitize(&n),
        Typ::Generic(n) => sanitize(&n),
    }
}

fn sanitize(name: &str) -> String {
    let s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() {
        "_".into()
    } else if s.as_bytes()[0].is_ascii_digit() {
        format!("_{s}")
    } else {
        s
    }
}

fn emit_go(module: &UnifiedModule) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("// Generated by Inauguration source backend (Go)\n");
    out.push_str("package main\n\n");
    if let Some(pkg) = &module.identity.package {
        out.push_str(&format!("// package: {pkg}\n"));
    }
    if let Some(m) = &module.identity.module {
        out.push_str(&format!("// module: {m}\n"));
    }

    for decl in &module.decls {
        match decl {
            Decl::Struct { name, fields, .. } => {
                out.push_str(&format!("type {} struct {{\n", sanitize(name)));
                for (fname, ftype) in fields {
                    out.push_str(&format!("\t{} {}\n", go_export_name(fname), go_type(ftype)));
                }
                out.push_str("}\n\n");
            }
            Decl::Class {
                name,
                fields,
                methods,
                ..
            } => {
                out.push_str(&format!("type {} struct {{\n", sanitize(name)));
                for (fname, ftype) in fields {
                    out.push_str(&format!("\t{} {}\n", go_export_name(fname), go_type(ftype)));
                }
                out.push_str("}\n\n");
                for m in methods {
                    if let Decl::Function {
                        name: mname,
                        params,
                        ret,
                        body,
                        ..
                    } = m
                    {
                        emit_go_method(&mut out, name, mname, params, ret, body);
                    }
                }
            }
            Decl::Function {
                name,
                params,
                ret,
                body,
                ..
            } => {
                emit_go_fn(&mut out, name, params, ret, body);
            }
            Decl::Global {
                name, typ, init, ..
            } => {
                let init_s = init
                    .as_ref()
                    .map(|e| format!(" = {}", go_expr(e)))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "var {} {}{}\n",
                    sanitize(name),
                    go_type(typ),
                    init_s
                ));
            }
            Decl::Interface { name, methods, .. } => {
                out.push_str(&format!("type {} interface {{\n", sanitize(name)));
                for m in methods {
                    let ps: Vec<String> = m
                        .params
                        .iter()
                        .map(|(n, t)| format!("{} {}", sanitize(n), go_type(t)))
                        .collect();
                    let r = go_type(&m.ret);
                    if r.is_empty() {
                        out.push_str(&format!(
                            "\t{}({})\n",
                            go_export_name(&m.name),
                            ps.join(", ")
                        ));
                    } else {
                        out.push_str(&format!(
                            "\t{}({}) {}\n",
                            go_export_name(&m.name),
                            ps.join(", "),
                            r
                        ));
                    }
                }
                out.push_str("}\n\n");
            }
            Decl::Component { name, target, .. } => {
                out.push_str(&format!("// component {name} target={target}\n"));
            }
        }
    }
    Ok(out)
}

fn go_export_name(name: &str) -> String {
    let s = sanitize(name);
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => format!("{}{}", c.to_ascii_uppercase(), chars.as_str()),
        None => "X".into(),
    }
}

fn emit_go_fn(out: &mut String, name: &str, params: &[(String, Typ)], ret: &Typ, body: &[Stmt]) {
    let ps: Vec<String> = params
        .iter()
        .map(|(n, t)| format!("{} {}", sanitize(n), go_type(t)))
        .collect();
    let r = go_type(ret);
    // Keep free-function names as-is so call sites match definitions.
    let fname = sanitize(name);
    if r.is_empty() || name == "main" {
        out.push_str(&format!("func {}({}) {{\n", fname, ps.join(", ")));
    } else {
        out.push_str(&format!("func {}({}) {} {{\n", fname, ps.join(", "), r));
    }
    for s in body {
        go_stmt(out, s, 1);
    }
    out.push_str("}\n\n");
}

fn emit_go_method(
    out: &mut String,
    recv: &str,
    name: &str,
    params: &[(String, Typ)],
    ret: &Typ,
    body: &[Stmt],
) {
    let ps: Vec<String> = params
        .iter()
        .map(|(n, t)| format!("{} {}", sanitize(n), go_type(t)))
        .collect();
    let r = go_type(ret);
    let recv_t = sanitize(recv);
    if r.is_empty() {
        out.push_str(&format!(
            "func (self *{}) {}({}) {{\n",
            recv_t,
            go_export_name(name),
            ps.join(", ")
        ));
    } else {
        out.push_str(&format!(
            "func (self *{}) {}({}) {} {{\n",
            recv_t,
            go_export_name(name),
            ps.join(", "),
            r
        ));
    }
    for s in body {
        go_stmt(out, s, 1);
    }
    out.push_str("}\n\n");
}

fn go_expr(expr: &Expr) -> String {
    match expr {
        Expr::IntLit(n) => format!("{n}"),
        Expr::FloatLit(f) => format!("{:?}", f.0),
        Expr::BoolLit(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::StringLit(s) => format!("{:?}", s),
        Expr::Ident(n) => sanitize(n),
        Expr::Unary { op, expr } => {
            let e = go_expr(expr);
            match op.as_str() {
                "neg" | "-" => format!("(-{e})"),
                "not" | "!" => format!("(!{e})"),
                _ => format!("({op}{e})"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = go_expr(lhs);
            let r = go_expr(rhs);
            let o = match op.as_str() {
                "add" | "+" => "+",
                "sub" | "-" => "-",
                "mul" | "*" => "*",
                "div" | "/" => "/",
                "mod" | "%" => "%",
                "eq" | "==" => "==",
                "neq" | "!=" => "!=",
                "lt" | "<" => "<",
                "gt" | ">" => ">",
                "le" | "<=" => "<=",
                "ge" | ">=" => ">=",
                "land" | "&&" => "&&",
                "lor" | "||" => "||",
                "band" | "&" => "&",
                "bor" | "|" => "|",
                "xor" | "^" => "^",
                "shl" | "<<" => "<<",
                "shr" | ">>" => ">>",
                other => other,
            };
            format!("({l} {o} {r})")
        }
        Expr::Call { callee, args } => {
            if let Expr::Field { base, name } = &**callee {
                let as_: Vec<String> = args.iter().map(go_expr).collect();
                return format!(
                    "{}.{}({})",
                    go_expr(base),
                    go_export_name(name),
                    as_.join(", ")
                );
            }
            let c = go_expr(callee);
            let as_: Vec<String> = args.iter().map(go_expr).collect();
            format!("{c}({})", as_.join(", "))
        }
        Expr::Field { base, name } => format!("{}.{}", go_expr(base), go_export_name(name)),
        Expr::StructInit { name, fields } => {
            let fs: Vec<String> = fields
                .iter()
                .map(|(n, e)| format!("{}: {}", go_export_name(n), go_expr(e)))
                .collect();
            format!("{}{{{}}}", sanitize(name), fs.join(", "))
        }
        Expr::Index { base, index } => format!("{}[{}]", go_expr(base), go_expr(index)),
        Expr::ArrayLit(items) => {
            let els: Vec<String> = items.iter().map(go_expr).collect();
            format!("[]int64{{{}}}", els.join(", "))
        }
        Expr::Closure { params, body, .. } => {
            let ps: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{} {}", sanitize(n), go_type(t)))
                .collect();
            let mut inner = String::new();
            for s in body {
                go_stmt(&mut inner, s, 2);
            }
            format!("func({}) {{\n{inner}\t}}", ps.join(", "))
        }
    }
}

fn go_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    let pad = "\t".repeat(indent);
    match stmt {
        Stmt::Let(name, _, expr) => {
            out.push_str(&format!("{pad}{} := {}\n", sanitize(name), go_expr(expr)));
        }
        Stmt::Assign(name, expr) => {
            out.push_str(&format!("{pad}{} = {}\n", sanitize(name), go_expr(expr)));
        }
        Stmt::IndexAssign { base, index, value } => {
            out.push_str(&format!(
                "{pad}{}[{}] = {}\n",
                go_expr(base),
                go_expr(index),
                go_expr(value)
            ));
        }
        Stmt::FieldAssign { base, name, value } => {
            out.push_str(&format!(
                "{pad}{}.{} = {}\n",
                go_expr(base),
                go_export_name(name),
                go_expr(value)
            ));
        }
        Stmt::Return(e) => match e {
            Some(x) => out.push_str(&format!("{pad}return {}\n", go_expr(x))),
            None => out.push_str(&format!("{pad}return\n")),
        },
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            out.push_str(&format!("{pad}if {} {{\n", go_expr(cond)));
            for s in then_body {
                go_stmt(out, s, indent + 1);
            }
            if !else_body.is_empty() {
                out.push_str(&format!("{pad}}} else {{\n"));
                for s in else_body {
                    go_stmt(out, s, indent + 1);
                }
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Loop { kind, cond, body } => match kind {
            LoopKind::For { binding } => {
                let iter = cond.as_ref().map(go_expr).unwrap_or_else(|| "nil".into());
                out.push_str(&format!(
                    "{pad}for _, {} := range {} {{\n",
                    sanitize(binding),
                    iter
                ));
                for s in body {
                    go_stmt(out, s, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
            LoopKind::While | LoopKind::Infinite => {
                match cond {
                    Some(c) => out.push_str(&format!("{pad}for {} {{\n", go_expr(c))),
                    None => out.push_str(&format!("{pad}for {{\n")),
                }
                for s in body {
                    go_stmt(out, s, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
        },
        Stmt::Match { scrutinee, arms } => {
            out.push_str(&format!("{pad}switch {} {{\n", go_expr(scrutinee)));
            for arm in arms {
                let p = arm.pattern.trim();
                if p == "_" || p == "else" || p == "default" {
                    out.push_str(&format!("{pad}default:\n"));
                } else {
                    out.push_str(&format!("{pad}case {p}:\n"));
                }
                for s in &arm.body {
                    go_stmt(out, s, indent + 1);
                }
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Throw(e) => {
            out.push_str(&format!("{pad}panic({})\n", go_expr(e)));
        }
        Stmt::Try { body, catches } => {
            out.push_str(&format!("{pad}// try\n{pad}func() {{\n"));
            out.push_str(&format!("{pad}\tdefer func() {{\n"));
            out.push_str(&format!("{pad}\t\tif r := recover(); r != nil {{\n"));
            if let Some(c) = catches.first() {
                let bind = c.pattern.trim();
                if is_ident(bind) {
                    out.push_str(&format!("{pad}\t\t\t{} := r\n", sanitize(bind)));
                    let _ = bind;
                }
                for s in &c.body {
                    go_stmt(out, s, indent + 3);
                }
            }
            out.push_str(&format!("{pad}\t\t}}\n{pad}\t}}()\n"));
            for s in body {
                go_stmt(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}()\n"));
        }
        Stmt::Propagate => out.push_str(&format!("{pad}// propagate\n")),
        Stmt::Expr(e) => out.push_str(&format!("{pad}{}\n", go_expr(e))),
        Stmt::Break => out.push_str(&format!("{pad}break\n")),
    }
}

fn emit_rust(module: &UnifiedModule) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("// Generated by Inauguration source backend (Rust)\n");
    if let Some(pkg) = &module.identity.package {
        out.push_str(&format!("// package: {pkg}\n"));
    }
    if let Some(m) = &module.identity.module {
        out.push_str(&format!("// module: {m}\n"));
    }
    out.push('\n');

    for decl in &module.decls {
        match decl {
            Decl::Struct { name, fields, .. } => {
                out.push_str(&format!("struct {} {{\n", sanitize(name)));
                for (fname, ftype) in fields {
                    out.push_str(&format!("    {}: {},\n", sanitize(fname), rust_type(ftype)));
                }
                out.push_str("}\n\n");
            }
            Decl::Class {
                name,
                fields,
                methods,
                ..
            } => {
                out.push_str(&format!("struct {} {{\n", sanitize(name)));
                for (fname, ftype) in fields {
                    out.push_str(&format!("    {}: {},\n", sanitize(fname), rust_type(ftype)));
                }
                out.push_str("}\n\n");
                out.push_str(&format!("impl {} {{\n", sanitize(name)));
                for m in methods {
                    if let Decl::Function {
                        name: mname,
                        params,
                        ret,
                        body,
                        ..
                    } = m
                    {
                        emit_rust_method(&mut out, mname, params, ret, body);
                    }
                }
                out.push_str("}\n\n");
            }
            Decl::Function {
                name,
                params,
                ret,
                body,
                ..
            } => {
                emit_rust_fn(&mut out, name, params, ret, body, false);
            }
            Decl::Global {
                name, typ, init, ..
            } => {
                let init_s = init
                    .as_ref()
                    .map(|e| format!(" = {}", rust_expr(e)))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "static {}: {}{};\n",
                    sanitize(name),
                    rust_type(typ),
                    init_s
                ));
            }
            Decl::Interface { name, methods, .. } => {
                out.push_str(&format!("trait {} {{\n", sanitize(name)));
                for m in methods {
                    let ps: Vec<String> = m
                        .params
                        .iter()
                        .map(|(n, t)| format!("{}: {}", sanitize(n), rust_type(t)))
                        .collect();
                    out.push_str(&format!(
                        "    fn {}({}) -> {};\n",
                        sanitize(&m.name),
                        ps.join(", "),
                        rust_type(&m.ret)
                    ));
                }
                out.push_str("}\n\n");
            }
            Decl::Component { name, target, .. } => {
                out.push_str(&format!("// component {name} target={target}\n"));
            }
        }
    }
    Ok(out)
}

fn emit_rust_fn(
    out: &mut String,
    name: &str,
    params: &[(String, Typ)],
    ret: &Typ,
    body: &[Stmt],
    in_impl: bool,
) {
    let pad = if in_impl { "    " } else { "" };
    let ps: Vec<String> = params
        .iter()
        .map(|(n, t)| format!("{}: {}", sanitize(n), rust_type(t)))
        .collect();
    let r = rust_type(ret);
    out.push_str(&format!(
        "{pad}fn {}({}) -> {} {{\n",
        sanitize(name),
        ps.join(", "),
        r
    ));
    for s in body {
        rust_stmt(out, s, if in_impl { 2 } else { 1 });
    }
    out.push_str(&format!("{pad}}}\n\n"));
}

fn emit_rust_method(
    out: &mut String,
    name: &str,
    params: &[(String, Typ)],
    ret: &Typ,
    body: &[Stmt],
) {
    let mut full = vec![("self".into(), Typ::Named("Self".into()))];
    full.extend(params.iter().cloned());
    // Fix Self type printing
    let ps: Vec<String> = std::iter::once("&mut self".to_string())
        .chain(
            params
                .iter()
                .map(|(n, t)| format!("{}: {}", sanitize(n), rust_type(t))),
        )
        .collect();
    let r = rust_type(ret);
    out.push_str(&format!(
        "    fn {}({}) -> {} {{\n",
        sanitize(name),
        ps.join(", "),
        r
    ));
    for s in body {
        rust_stmt(out, s, 2);
    }
    out.push_str("    }\n\n");
}

fn rust_expr(expr: &Expr) -> String {
    match expr {
        Expr::IntLit(n) => format!("{n}"),
        Expr::FloatLit(f) => format!("{:?}", f.0),
        Expr::BoolLit(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::StringLit(s) => format!("{:?}.to_string()", s),
        Expr::Ident(n) => sanitize(n),
        Expr::Unary { op, expr } => {
            let e = rust_expr(expr);
            match op.as_str() {
                "neg" | "-" => format!("(-{e})"),
                "not" | "!" => format!("(!{e})"),
                _ => format!("({op}{e})"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = rust_expr(lhs);
            let r = rust_expr(rhs);
            let o = match op.as_str() {
                "add" | "+" => "+",
                "sub" | "-" => "-",
                "mul" | "*" => "*",
                "div" | "/" => "/",
                "mod" | "%" => "%",
                "eq" | "==" => "==",
                "neq" | "!=" => "!=",
                "lt" | "<" => "<",
                "gt" | ">" => ">",
                "le" | "<=" => "<=",
                "ge" | ">=" => ">=",
                "land" | "&&" => "&&",
                "lor" | "||" => "||",
                "band" | "&" => "&",
                "bor" | "|" => "|",
                "xor" | "^" => "^",
                "shl" | "<<" => "<<",
                "shr" | ">>" => ">>",
                other => other,
            };
            format!("({l} {o} {r})")
        }
        Expr::Call { callee, args } => {
            if let Expr::Field { base, name } = &**callee {
                let as_: Vec<String> = args.iter().map(rust_expr).collect();
                return format!("{}.{}({})", rust_expr(base), sanitize(name), as_.join(", "));
            }
            let c = rust_expr(callee);
            let as_: Vec<String> = args.iter().map(rust_expr).collect();
            format!("{c}({})", as_.join(", "))
        }
        Expr::Field { base, name } => format!("{}.{}", rust_expr(base), sanitize(name)),
        Expr::StructInit { name, fields } => {
            let fs: Vec<String> = fields
                .iter()
                .map(|(n, e)| format!("{}: {}", sanitize(n), rust_expr(e)))
                .collect();
            format!("{} {{ {} }}", sanitize(name), fs.join(", "))
        }
        Expr::Index { base, index } => format!("{}[{}]", rust_expr(base), rust_expr(index)),
        Expr::ArrayLit(items) => {
            let els: Vec<String> = items.iter().map(rust_expr).collect();
            format!("vec![{}]", els.join(", "))
        }
        Expr::Closure {
            params,
            body,
            captures,
            ..
        } => {
            let move_kw = if captures.is_empty() { "" } else { "move " };
            let ps: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{}: {}", sanitize(n), rust_type(t)))
                .collect();
            let mut inner = String::new();
            for s in body {
                rust_stmt(&mut inner, s, 2);
            }
            format!("{move_kw}|{}| {{\n{inner}    }}", ps.join(", "))
        }
    }
}

fn rust_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        Stmt::Let(name, typ, expr) => {
            let ty = typ
                .as_ref()
                .map(|t| format!(": {}", rust_type(t)))
                .unwrap_or_default();
            out.push_str(&format!(
                "{pad}let mut {}{} = {};\n",
                sanitize(name),
                ty,
                rust_expr(expr)
            ));
        }
        Stmt::Assign(name, expr) => {
            out.push_str(&format!("{pad}{} = {};\n", sanitize(name), rust_expr(expr)));
        }
        Stmt::IndexAssign { base, index, value } => {
            out.push_str(&format!(
                "{pad}{}[{}] = {};\n",
                rust_expr(base),
                rust_expr(index),
                rust_expr(value)
            ));
        }
        Stmt::FieldAssign { base, name, value } => {
            out.push_str(&format!(
                "{pad}{}.{} = {};\n",
                rust_expr(base),
                sanitize(name),
                rust_expr(value)
            ));
        }
        Stmt::Return(e) => match e {
            Some(x) => out.push_str(&format!("{pad}return {};\n", rust_expr(x))),
            None => out.push_str(&format!("{pad}return;\n")),
        },
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            out.push_str(&format!("{pad}if {} {{\n", rust_expr(cond)));
            for s in then_body {
                rust_stmt(out, s, indent + 1);
            }
            if !else_body.is_empty() {
                out.push_str(&format!("{pad}}} else {{\n"));
                for s in else_body {
                    rust_stmt(out, s, indent + 1);
                }
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Loop { kind, cond, body } => match kind {
            LoopKind::For { binding } => {
                let iter = cond.as_ref().map(rust_expr).unwrap_or_else(|| "[]".into());
                out.push_str(&format!("{pad}for {} in {iter} {{\n", sanitize(binding)));
                for s in body {
                    rust_stmt(out, s, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
            LoopKind::While => {
                let c = cond
                    .as_ref()
                    .map(rust_expr)
                    .unwrap_or_else(|| "true".into());
                out.push_str(&format!("{pad}while {c} {{\n"));
                for s in body {
                    rust_stmt(out, s, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
            LoopKind::Infinite => {
                out.push_str(&format!("{pad}loop {{\n"));
                for s in body {
                    rust_stmt(out, s, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
        },
        Stmt::Match { scrutinee, arms } => {
            out.push_str(&format!("{pad}match {} {{\n", rust_expr(scrutinee)));
            for arm in arms {
                out.push_str(&format!("{pad}    {} => {{\n", arm.pattern.trim()));
                for s in &arm.body {
                    rust_stmt(out, s, indent + 2);
                }
                out.push_str(&format!("{pad}    }}\n"));
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Throw(e) => {
            out.push_str(&format!("{pad}panic!(\"{{:?}}\", {});\n", rust_expr(e)));
        }
        Stmt::Try { body, catches } => {
            out.push_str(&format!("{pad}// try (lossy)\n{pad}{{\n"));
            for s in body {
                rust_stmt(out, s, indent + 1);
            }
            out.push_str(&format!("{pad}}}\n"));
            for c in catches {
                out.push_str(&format!("{pad}// catch {}\n", c.pattern));
                for s in &c.body {
                    rust_stmt(out, s, indent);
                }
            }
        }
        Stmt::Propagate => out.push_str(&format!("{pad}// propagate\n")),
        Stmt::Expr(e) => out.push_str(&format!("{pad}{};\n", rust_expr(e))),
        Stmt::Break => out.push_str(&format!("{pad}break;\n")),
    }
}

fn is_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core_ir::{Expr, Stmt, Typ};

    #[test]
    fn go_emits_fn_and_if() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "answer".into(),
            params: vec![],
            ret: Typ::Int,
            body: vec![Stmt::If {
                cond: Expr::BoolLit(true),
                then_body: vec![Stmt::Return(Some(Expr::IntLit(42)))],
                else_body: vec![Stmt::Return(Some(Expr::IntLit(0)))],
            }],
            type_params: vec![],
        }]);
        let go = emit_source_module(&module, SourceLang::Go).expect("go");
        assert!(go.contains("package main"), "{go}");
        assert!(go.contains("func answer()"), "{go}");
        assert!(go.contains("if true"), "{go}");
        assert!(go.contains("return 42"), "{go}");
    }

    #[test]
    fn rust_emits_fn_and_while() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "loop_sum".into(),
            params: vec![("n".into(), Typ::Int)],
            ret: Typ::Int,
            body: vec![
                Stmt::Let("i".into(), Some(Typ::Int), Expr::IntLit(0)),
                Stmt::Loop {
                    kind: LoopKind::While,
                    cond: Some(Expr::Binary {
                        op: "lt".into(),
                        lhs: Box::new(Expr::Ident("i".into())),
                        rhs: Box::new(Expr::Ident("n".into())),
                    }),
                    body: vec![Stmt::Assign(
                        "i".into(),
                        Expr::Binary {
                            op: "add".into(),
                            lhs: Box::new(Expr::Ident("i".into())),
                            rhs: Box::new(Expr::IntLit(1)),
                        },
                    )],
                },
                Stmt::Return(Some(Expr::Ident("i".into()))),
            ],
            type_params: vec![],
        }]);
        let rs = emit_source_module(&module, SourceLang::Rust).expect("rust");
        assert!(rs.contains("fn loop_sum(n: i64) -> i64"), "{rs}");
        assert!(rs.contains("while"), "{rs}");
        assert!(rs.contains("let mut i: i64 = 0"), "{rs}");
    }

    #[test]
    fn go_and_rust_emit_struct() {
        let module = UnifiedModule::new(vec![
            Decl::Struct {
                name: "Point".into(),
                fields: vec![("x".into(), Typ::Int), ("y".into(), Typ::Int)],
                type_params: vec![],
            },
            Decl::Function {
                name: "origin".into(),
                params: vec![],
                ret: Typ::Named("Point".into()),
                body: vec![Stmt::Return(Some(Expr::StructInit {
                    name: "Point".into(),
                    fields: vec![("x".into(), Expr::IntLit(0)), ("y".into(), Expr::IntLit(0))],
                }))],
                type_params: vec![],
            },
        ]);
        let go = emit_source_module(&module, SourceLang::Go).expect("go");
        let rs = emit_source_module(&module, SourceLang::Rust).expect("rs");
        assert!(go.contains("type Point struct"), "{go}");
        assert!(
            go.contains("Point{X: 0, Y: 0}") || go.contains("Point{"),
            "{go}"
        );
        assert!(rs.contains("struct Point"), "{rs}");
        assert!(rs.contains("Point {"), "{rs}");
    }
}
